Set Warnings "-notation-overridden".
Set Warnings "-ambiguous-paths".

Require Import List Lia PeanoNat Arith.

From mathcomp Require Import ssreflect ssrbool eqtype seq ssrnat ssralg.

From PTree.Prob Require Import RatSubTypes DiscreteMC.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import Enum.
Import RatSubTypes.
Import GRing.Theory.
#[local] Open Scope ring_scope.

Lemma bind_Enum_app {A B}
    (mu nu : Enum A) (k : A -> Enum B) :
  bind_Enum (mu ++ nu) k =
  bind_Enum mu k ++ bind_Enum nu k.
Proof.
  elim: mu => [//=|[p a] mu IH] //=.
  by rewrite IH catA.
Qed.

Lemma bind_Enum_scale {A B}
    (p : nnQ) (mu : Enum A) (k : A -> Enum B) :
  bind_Enum (scale_Enum p mu) k =
  scale_Enum p (bind_Enum mu k).
Proof.
  elim: mu => [//=|[q a] mu IH] //=.
  by rewrite IH scale_app !scale_scale.
Qed.

Lemma bind_Enum_assoc {A B C}
    (mu : Enum A) (k : A -> Enum B) (h : B -> Enum C) :
  bind_Enum (bind_Enum mu k) h =
  bind_Enum mu (fun x => bind_Enum (k x) h).
Proof.
  elim: mu => [//=|[p a] mu IH] //=.
  by rewrite bind_Enum_app bind_Enum_scale IH.
Qed.

Lemma bind_Enum_ext {A B}
    (mu : Enum A) (k1 k2 : A -> Enum B) :
  (forall x, k1 x = k2 x) ->
  bind_Enum mu k1 = bind_Enum mu k2.
Proof.
  move=> Hk.
  elim: mu => [//=|[p a] mu IH] //=.
  by rewrite Hk IH.
Qed.

Lemma acc_mass_scale {A : eqType} (x : A) p (mu : Enum A) :
  acc_mass x (scale_Enum p mu) = p * acc_mass x mu.
Proof.
  revert p.
  refine (list_ind (fun mu => forall p,
    acc_mass x (scale_Enum p mu) = p * acc_mass x mu) _ _ mu).
  - intro p. rewrite /= mulr0. reflexivity.
  - intros [q a] tl IH p.
    change (acc_mass x ((p * q, a) :: scale_Enum p tl) =
      p * acc_mass x ((q, a) :: tl)).
    rewrite !acc_mass_cons IH.
    destruct (a == x) eqn:Hax.
    + move/eqP: Hax=> Hax. subst a.
      rewrite !eq_refl -mulrDr. reflexivity.
    + rewrite Hax !addr0. reflexivity.
Qed.

Lemma scale_Enum_proper {A : eqType} p (mu nu : Enum A) :
  mu ==Enum nu -> scale_Enum p mu ==Enum scale_Enum p nu.
Proof. move=> H x. by rewrite !acc_mass_scale H. Qed.

Lemma app_Enum_proper {A : eqType} (mu mu' nu nu' : Enum A) :
  mu ==Enum mu' -> nu ==Enum nu' -> mu ++ nu ==Enum mu' ++ nu'.
Proof. move=> Hmu Hnu x. by rewrite !acc_app Hmu Hnu. Qed.

Lemma bind_Enum_pointwise_proper {A} {B : eqType}
    (mu : Enum A) (k1 k2 : A -> Enum B) :
  (forall a, k1 a ==Enum k2 a) ->
  bind_Enum mu k1 ==Enum bind_Enum mu k2.
Proof.
  move=> Hk. elim: mu=> [|[p a] mu IH] //=.
  apply app_Enum_proper.
  - exact: scale_Enum_proper (Hk a).
  - exact IH.
Qed.

(** Starting position of the continuation block generated by the [i]-th
    entry of an outer enumeration. *)
Fixpoint bind_offset {A B} (mu : Enum A) (k : A -> Enum B)
    (i : nat) : nat :=
  match mu, i with
  | [::], _ => 0
  | _, 0 => 0
  | (_, a) :: tl, i'.+1 => (size (k a) + bind_offset tl k i')%N
  end.

Lemma size_scale_Enum {A} p (mu : Enum A) :
  size (scale_Enum p mu) = size mu.
Proof. by elim: mu=> [|[q a] mu IH] //=; rewrite IH. Qed.

Lemma nth_error_scale_Enum {A} p (mu : Enum A) i q a :
  nth_error mu i = Some (q, a) ->
  nth_error (scale_Enum p mu) i = Some (p * q, a).
Proof.
  elim: mu i=> [|[r x] mu IH] [|i] //=.
  - by move=> H; inversion H; subst.
  - exact: IH.
Qed.

Lemma nth_error_app_right {A} (xs ys : seq A) i y :
  nth_error ys i = Some y ->
  nth_error (xs ++ ys) (size xs + i)%N = Some y.
Proof.
  by elim: xs=> [|x xs IH] //=.
Qed.

Lemma nth_error_app_left {A} (xs ys : seq A) i x :
  nth_error xs i = Some x ->
  nth_error (xs ++ ys) i = Some x.
Proof.
  elim: xs i=> [|y xs IH] [|i] //=.
  exact: IH.
Qed.

Lemma nth_error_scale_Enum_inv {A} p (mu : Enum A) i w a :
  nth_error (scale_Enum p mu) i = Some (w, a) ->
  exists q, nth_error mu i = Some (q, a) /\ w = p * q.
Proof.
  elim: mu i=> [|[q b] mu IH] [|i] //=.
  - move=> H. inversion H; subst. by exists q.
  - exact: IH.
Qed.

Lemma nth_error_app_inv {A} (xs ys : seq A) n z :
  nth_error (xs ++ ys) n = Some z ->
  (Peano.lt n (size xs) /\ nth_error xs n = Some z) \/
  exists j, n = (size xs + j)%N /\ nth_error ys j = Some z.
Proof.
  move=> H.
  destruct (PeanoNat.Nat.lt_ge_cases n (size xs)) as [Hlt|Hge].
  - left. split=> //.
    rewrite -(@nth_error_app1 A xs ys n Hlt). exact H.
  - right. exists (n - size xs)%N. split.
    + change (n = size xs + (n - size xs))%coq_nat.
      rewrite Nat.add_comm. symmetry. apply Nat.sub_add. exact Hge.
    + rewrite -(@nth_error_app2 A xs ys n Hge). exact H.
Qed.

(** Exact position and weight of an entry after flattening an Enum bind. *)
Lemma nth_error_bind_Enum {A B} (mu : Enum A) (k : A -> Enum B)
    i j p a q b :
  nth_error mu i = Some (p, a) ->
  nth_error (k a) j = Some (q, b) ->
  nth_error (bind_Enum mu k) (bind_offset mu k i + j)%N =
    Some (p * q, b).
Proof.
  elim: mu i p a=> [|[r x] mu IH] [|i] p a //=.
  - move=> Houter Hinner. inversion Houter; subst r x.
    apply nth_error_app_left.
    apply nth_error_scale_Enum. exact Hinner.
  - move=> Houter Hinner.
    have Htail := IH i p a Houter Hinner.
    have Happ := @nth_error_app_right (nnQ * B)
      (scale_Enum r (k x)) (bind_Enum mu k)
      (bind_offset mu k i + j)%N (p * q, b) Htail.
    rewrite size_scale_Enum in Happ.
    replace (size (k x) + bind_offset mu k i + j)%N
      with (size (k x) + (bind_offset mu k i + j))%N.
    - exact Happ.
    - apply PeanoNat.Nat.add_assoc.
Qed.

(** Every successful position in a flattened bind comes from an outer entry
    and one entry of its continuation block. *)
Lemma nth_error_bind_Enum_inv {A B} (mu : Enum A) (k : A -> Enum B)
    n w b :
  nth_error (bind_Enum mu k) n = Some (w, b) ->
  exists i j p a q,
    nth_error mu i = Some (p, a) /\
    nth_error (k a) j = Some (q, b) /\
    n = (bind_offset mu k i + j)%N /\ w = p * q.
Proof.
  elim: mu n=> [|[p a] mu IH] n Hnth.
  - destruct n; cbn in Hnth; discriminate.
  - cbn in Hnth.
    move: (nth_error_app_inv Hnth)=> [[Hlt Hhead]|[n' [Hn Htail]]].
    + move: (nth_error_scale_Enum_inv Hhead)=> [q [Hq ->]].
      exists 0%N, n, p, a, q. repeat split=> //.
    + rewrite size_scale_Enum in Hn.
      move: (IH n' Htail)=> [i [j [r [x [q [Hi [Hj [Hoff Hw]]]]]]]].
      exists i.+1, j, r, x, q. repeat split=> //.
      rewrite Hn Hoff /=.
      rewrite addnA. reflexivity.
Qed.
