Set Warnings "-notation-overridden".
Set Warnings "-ambiguous-paths".

Require Import List Lia PeanoNat.

From mathcomp Require Import ssreflect seq ssrnat ssralg.

From PTree.Prob Require Import RatSubTypes DiscreteMC.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import Enum.
Import RatSubTypes.
Import GRing.Theory.
#[local] Open Scope ring_scope.

Lemma bind_Enum_app {A B}
    (mu nu : Enum A) (k : A -> Enum B) :
  bind_Enum (mu ++ nu) k =
  bind_Enum mu k ++ bind_Enum nu k.
Proof.
  elim: mu => [//=|[p a] mu IH] //=.
  by rewrite IH catA.
Qed.

Lemma bind_Enum_scale {A B}
    (p : nnQ) (mu : Enum A) (k : A -> Enum B) :
  bind_Enum (scale_Enum p mu) k =
  scale_Enum p (bind_Enum mu k).
Proof.
  elim: mu => [//=|[q a] mu IH] //=.
  by rewrite IH scale_app !scale_scale.
Qed.

Lemma bind_Enum_assoc {A B C}
    (mu : Enum A) (k : A -> Enum B) (h : B -> Enum C) :
  bind_Enum (bind_Enum mu k) h =
  bind_Enum mu (fun x => bind_Enum (k x) h).
Proof.
  elim: mu => [//=|[p a] mu IH] //=.
  by rewrite bind_Enum_app bind_Enum_scale IH.
Qed.

Lemma bind_Enum_ext {A B}
    (mu : Enum A) (k1 k2 : A -> Enum B) :
  (forall x, k1 x = k2 x) ->
  bind_Enum mu k1 = bind_Enum mu k2.
Proof.
  move=> Hk.
  elim: mu => [//=|[p a] mu IH] //=.
  by rewrite Hk IH.
Qed.

(** Starting position of the continuation block generated by the [i]-th
    entry of an outer enumeration. *)
Fixpoint bind_offset {A B} (mu : Enum A) (k : A -> Enum B)
    (i : nat) : nat :=
  match mu, i with
  | [::], _ => 0
  | _, 0 => 0
  | (_, a) :: tl, i'.+1 => (size (k a) + bind_offset tl k i')%N
  end.

Lemma size_scale_Enum {A} p (mu : Enum A) :
  size (scale_Enum p mu) = size mu.
Proof. by elim: mu=> [|[q a] mu IH] //=; rewrite IH. Qed.

Lemma nth_error_scale_Enum {A} p (mu : Enum A) i q a :
  nth_error mu i = Some (q, a) ->
  nth_error (scale_Enum p mu) i = Some (p * q, a).
Proof.
  elim: mu i=> [|[r x] mu IH] [|i] //=.
  - by move=> H; inversion H; subst.
  - exact: IH.
Qed.

Lemma nth_error_app_right {A} (xs ys : seq A) i y :
  nth_error ys i = Some y ->
  nth_error (xs ++ ys) (size xs + i)%N = Some y.
Proof.
  by elim: xs=> [|x xs IH] //=.
Qed.

Lemma nth_error_app_left {A} (xs ys : seq A) i x :
  nth_error xs i = Some x ->
  nth_error (xs ++ ys) i = Some x.
Proof.
  elim: xs i=> [|y xs IH] [|i] //=.
  exact: IH.
Qed.

(** Exact position and weight of an entry after flattening an Enum bind. *)
Lemma nth_error_bind_Enum {A B} (mu : Enum A) (k : A -> Enum B)
    i j p a q b :
  nth_error mu i = Some (p, a) ->
  nth_error (k a) j = Some (q, b) ->
  nth_error (bind_Enum mu k) (bind_offset mu k i + j)%N =
    Some (p * q, b).
Proof.
  elim: mu i p a=> [|[r x] mu IH] [|i] p a //=.
  - move=> Houter Hinner. inversion Houter; subst r x.
    apply nth_error_app_left.
    apply nth_error_scale_Enum. exact Hinner.
  - move=> Houter Hinner.
    have Htail := IH i p a Houter Hinner.
    have Happ := @nth_error_app_right (nnQ * B)
      (scale_Enum r (k x)) (bind_Enum mu k)
      (bind_offset mu k i + j)%N (p * q, b) Htail.
    rewrite size_scale_Enum in Happ.
    replace (size (k x) + bind_offset mu k i + j)%N
      with (size (k x) + (bind_offset mu k i + j))%N.
    - exact Happ.
    - apply PeanoNat.Nat.add_assoc.
Qed.
