(include_subdirs qualified)

(coq.theory
 (name PTree)
 (package coq-ptree)
 (modules
  :standard)
 (theories
   ExtLib
   ITree
   Paco
   Coinduction
   ;; ProbAx

   ;; math comp
   mathcomp
   HB
   mathcomp.analysis
   elpi
   elpi_elpi
 )
 (flags -w -notation-incompatible-prefix -w -notation-overridden))
