(** Integration regression: load every module in one universe context.
    Not a facade or an ordinary theorem client. *)
Require PTree.API.Enum.
Require PTree.API.FreeOmega.
Require PTree.API.Generic.
Require PTree.API.SubEnum.
Require PTree.API.Weighted.
Require PTree.CaseStudies.BernoulliFactory.BernoulliFactory.
Require PTree.CaseStudies.BernoulliFactory.BernoulliFactoryComposition.
Require PTree.CaseStudies.BernoulliFactory.BernoulliFactoryProbability.
Require PTree.CaseStudies.BernoulliFactory.OperationalBernoulliFactory.
Require PTree.CaseStudies.BernoulliFactory.OperationalRationalBernoulli.
Require PTree.CaseStudies.BernoulliFactory.OperationalRealBernoulliMathComp.
Require PTree.CaseStudies.BernoulliFactory.OperationalVonNeumann.
Require PTree.CaseStudies.BernoulliFactory.RationalBernoulli.
Require PTree.CaseStudies.BernoulliFactory.RealBernoulliMathComp.
Require PTree.CaseStudies.BernoulliFactory.RealBernoulliOracle.
Require PTree.CaseStudies.BernoulliFactory.UnifiedRealBernoulliMathCompCore.
Require PTree.CaseStudies.BernoulliFactory.VonNeumannUnbounded.
Require PTree.CaseStudies.InteractiveVonNeumann.InteractiveVonNeumannService.
Require PTree.CaseStudies.MixedHeadProtocol.
Require PTree.CaseStudies.RandomWalk.
Require PTree.Core.PTreeDefinition.
Require PTree.Core.Utils.
Require PTree.Eq.Backend.EnumCofinality.
Require PTree.Eq.Backend.ProbabilisticTraceEnum.
Require PTree.Eq.Backend.ProbabilisticTraceSubEnum.
Require PTree.Eq.FreeOmega.Algebra.
Require PTree.Eq.FreeOmega.Base.
Require PTree.Eq.FreeOmega.Bind.
Require PTree.Eq.FreeOmega.Hitting.
Require PTree.Eq.FreeOmega.Iter.
Require PTree.Eq.FreeOmega.Relation.
Require PTree.Eq.Internal.Backend.KernelDisintegration.
Require PTree.Eq.Internal.FiniteInternal.
Require PTree.Eq.Internal.FiniteInternalHitting.
Require PTree.Eq.Internal.FiniteInternalJoint.
Require PTree.Eq.Internal.FiniteInternalPlan.
Require PTree.Eq.Internal.FreeOmega.CostedKernel.
Require PTree.Eq.Internal.FreeOmega.FiniteInternal.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalAcceleration.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalCostedCoinduction.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalCostedProjection.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJoint.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointAcceleration.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointCoinduction.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointCoverage.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointHitting.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointReference.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointRows.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointTruncation.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalNative.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalNativeJoint.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalPlanHitting.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalProjectedPolicy.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalRound.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalRoundCoupling.
Require PTree.Eq.Internal.FreeOmega.KernelCompletion.
Require PTree.Eq.Internal.FreeOmega.KernelCongruence.
Require PTree.Eq.Internal.FreeOmega.KernelContinuity.
Require PTree.Eq.Internal.FreeOmega.KernelProjection.
Require PTree.Eq.PEutt.
Require PTree.Eq.PStrong.
Require PTree.Eq.PStruct.
Require PTree.Eq.PTreeKernel.
Require PTree.Eq.PrimitiveStableHitting.
Require PTree.Eq.ProbabilisticTrace.
Require PTree.Eq.Shallow.
Require PTree.Eq.StableHittingComputation.
Require PTree.Eq.StableHittingRelation.
Require PTree.Eq.UnifiedFrontier.
Require PTree.Eq.WellFormedness.
Require PTree.Interp.Backend.SubEnum.
Require PTree.Interp.FreeOmega.Atomic.
Require PTree.Interp.FreeOmega.Base.
Require PTree.Interp.FreeOmega.Cofinality.
Require PTree.Interp.FreeOmega.Guarded.
Require PTree.Interp.FreeOmega.MDP.
Require PTree.Interp.FreeOmega.Translate.
Require PTree.Interp.Kernel.
Require PTree.Interp.Structural.
Require PTree.PTree.
Require PTree.Prob.Backend.Coupling.
Require PTree.Prob.Backend.DiscreteMC.
Require PTree.Prob.Backend.EnumBindFacts.
Require PTree.Prob.Backend.EnumDisintegration.
Require PTree.Prob.Backend.EnumMap.
Require PTree.Prob.Backend.EnumSupport.
Require PTree.Prob.Backend.FinSupp.
Require PTree.Prob.Backend.FiniteCapacityMatching.
Require PTree.Prob.Backend.FiniteEnumPresentation.
Require PTree.Prob.Backend.FiniteEnumTransport.
Require PTree.Prob.Backend.FiniteMatching.
Require PTree.Prob.Backend.FiniteRationalTransport.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaCodedJointSubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaCouplingEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaDisintegration.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaEquivalenceJointSubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaMeasureEnumAudit.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaNativeCouplingSubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaNativeTransportEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaNativeTransportSubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaRecoverySubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaTotalSubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperContinuityEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperContinuitySubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperCouplingEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperCouplingSubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperExpectationEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperExpectationSubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperObservationEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperObservationSubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperQuotientEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperQuotientSubEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperRelationalEnum.
Require PTree.Prob.Backend.FreeOmega.FreeOmegaUpperRelationalSubEnum.
Require PTree.Prob.Backend.FrontierLiftEnum.
Require PTree.Prob.Backend.IndexedCoupling.
Require PTree.Prob.Backend.MathCompMeasure.
Require PTree.Prob.Backend.MeasureIterationEnum.
Require PTree.Prob.Backend.RatGeometric.
Require PTree.Prob.Backend.RatSubTypes.
Require PTree.Prob.Backend.RealSubTypes.
Require PTree.Prob.Backend.SemanticCouplingEnum.
Require PTree.Prob.Backend.SemanticCouplingMathComp.
Require PTree.Prob.Backend.TwoLevelMeasureEnum.
Require PTree.Prob.Backend.TwoLevelMeasureMathComp.
Require PTree.Prob.Backend.TwoLevelMeasureSubEnum.
Require PTree.Prob.FreeOmega.FreeOmegaCoupling.
Require PTree.Prob.FreeOmega.FreeOmegaJointExtension.
Require PTree.Prob.FreeOmega.FreeOmegaMeasure.
Require PTree.Prob.FreeOmega.FreeOmegaNative.
Require PTree.Prob.FreeOmega.FreeOmegaNativeCoupling.
Require PTree.Prob.FreeOmega.FreeOmegaRecovery.
Require PTree.Prob.FreeOmega.FreeOmegaSupport.
Require PTree.Prob.Interface.FrontierLift.
Require PTree.Prob.Interface.MeasureIteration.
Require PTree.Prob.Interface.SemanticCoupling.
Require PTree.Prob.Interface.TwoLevelMeasure.
Require PTree.Prob.Legacy.Discrete.
Require PTree.Prob.Legacy.Monad.
Require PTree.Prob.Legacy.MonadList.
Require PTree.Prob.Legacy.RelLift.
Require PTree.Regression.Backend.BackendCapabilities.
Require PTree.Regression.Backend.CouplingRealization.
Require PTree.Regression.Backend.EnumMeasureRegression.
Require PTree.Regression.Backend.ExtendedEnum.
Require PTree.Regression.Backend.FreeOmegaEscapingMass.
Require PTree.Regression.Backend.FreeOmegaLimitSafety.
Require PTree.Regression.Backend.FreeOmegaUpperContinuity.
Require PTree.Regression.Backend.FreeOmegaUpperExpectation.
Require PTree.Regression.Backend.FreeOmegaUpperObservation.
Require PTree.Regression.Backend.FreeOmegaUpperQuotient.
Require PTree.Regression.Backend.NativeReflection.
Require PTree.Regression.Backend.SubEnumRegression.
Require PTree.Regression.Backend.UnifiedFrontierEnum.
Require PTree.Regression.Backend.UnifiedMathCompFrontier.
Require PTree.Regression.Infrastructure.ArchitectureBoundaries.
Require PTree.Regression.Infrastructure.CorrelatedInternalRounds.
Require PTree.Regression.Infrastructure.CostedRounds.
Require PTree.Regression.Infrastructure.CouplingReferences.
Require PTree.Regression.Infrastructure.FiniteInternalNative.
Require PTree.Regression.Infrastructure.FiniteInternalPlan.
Require PTree.Regression.Infrastructure.FiniteInternalRound.
Require PTree.Regression.Infrastructure.HiddenRandomState.
Require PTree.Regression.Infrastructure.KernelCompletion.
Require PTree.Regression.Infrastructure.KernelCongruence.
Require PTree.Regression.Infrastructure.KernelContinuity.
Require PTree.Regression.Infrastructure.NativeRecovery.
Require PTree.Regression.Infrastructure.PairedFiniteCompression.
Require PTree.Regression.Infrastructure.ResidualFinite.
Require PTree.Regression.Infrastructure.ResidualJointCoinduction.
Require PTree.Regression.Infrastructure.ResidualTransport.
Require PTree.Regression.Infrastructure.UniverseSeparatedPTree.
Require PTree.Regression.Probability.ConditionalResampling.
Require PTree.Regression.Probability.CorrelatedSampleAlgebra.
Require PTree.Regression.Probability.EnumDisintegration.
Require PTree.Regression.Probability.FiniteTransport.
Require PTree.Regression.Semantics.AtomicInterp.
Require PTree.Regression.Semantics.CanonicalPartialDivergence.
Require PTree.Regression.Semantics.GuardedInterp.
Require PTree.Regression.Semantics.HeadTransition.
Require PTree.Regression.Semantics.HittingDivergence.
Require PTree.Regression.Semantics.InterpExposure.
Require PTree.Regression.Semantics.LabelledMDP.
Require PTree.Regression.Semantics.MDPCoincidence.
Require PTree.Regression.Semantics.MDPEmbedding.
Require PTree.Regression.Semantics.MDPFragment.
Require PTree.Regression.Semantics.MDPInterp.
Require PTree.Regression.Semantics.OperationalPTSExamples.
Require PTree.Regression.Semantics.PEuttAlgebra.
Require PTree.Regression.Semantics.PEuttNotation.
Require PTree.Regression.Semantics.ProbabilisticRelationHierarchy.
Require PTree.Regression.Semantics.PublicSemanticFacade.
Require PTree.Regression.Semantics.StableHittingComputation.
Require PTree.Regression.Semantics.TreeTransition.
Require PTree.Regression.Semantics.TreeTransitionBisim.
Require PTree.Regression.Semantics.TreeTransitionSoundness.
Require PTree.Regression.Semantics.TreeTransitionStrictness.
Require PTree.Semantics.
Require PTree.Semantics.Backend.MDPEmbeddingSubEnum.
Require PTree.Semantics.FreeOmega.MDPCoincidenceFreeOmega.
Require PTree.Semantics.HeadTransition.
Require PTree.Semantics.MDPCoincidence.
Require PTree.Semantics.MDPEmbedding.
Require PTree.Semantics.MDPFragment.
Require PTree.Semantics.TreeTransition.
Require PTree.Semantics.TreeTransitionBisim.
Require PTree.Semantics.TreeTransitionSoundness.
