(** Gate S integration regression: load every normally checked module in one universe context.
    Not a facade or an ordinary theorem client. *)
Require PTree.Core.Fold.
Require PTree.Core.Handler.
Require PTree.Core.IterationLaws.
Require PTree.Core.PTreeDefinition.
Require PTree.Core.Utils.
Require PTree.Eq.
Require PTree.Eq.Algebra.
Require PTree.Eq.Backend.EnumQ.
Require PTree.Eq.Backend.EnumQCofinality.
Require PTree.Eq.Backend.ProbabilisticTraceEnumQ.
Require PTree.Eq.Backend.ProbabilisticTraceSubEnumQ.
Require PTree.Eq.Backend.StableHittingDomainSubEnumQ.
Require PTree.Eq.Backend.SubEnumQ.
Require PTree.Eq.Backend.SubEnumR.
Require PTree.Eq.Bind.
Require PTree.Eq.BindScheduling.
Require PTree.Eq.Canonical.
Require PTree.Eq.FreeOmega.Algebra.
Require PTree.Eq.FreeOmega.Base.
Require PTree.Eq.FreeOmega.Bind.
Require PTree.Eq.FreeOmega.Canonical.
Require PTree.Eq.FreeOmega.Hitting.
Require PTree.Eq.FreeOmega.Iter.
Require PTree.Eq.FreeOmega.Relation.
Require PTree.Eq.Internal.Backend.KernelDisintegration.
Require PTree.Eq.Internal.FiniteInternal.
Require PTree.Eq.Internal.FiniteInternalHitting.
Require PTree.Eq.Internal.FiniteInternalJoint.
Require PTree.Eq.Internal.FiniteInternalPlan.
Require PTree.Eq.Internal.FreeOmega.CostedKernel.
Require PTree.Eq.Internal.FreeOmega.FiniteInternal.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalAcceleration.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalCostedCoinduction.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalCostedProjection.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJoint.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointAcceleration.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointCoinduction.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointCoverage.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointHitting.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointReference.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointRows.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalJointTruncation.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalNative.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalNativeJoint.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalPlanHitting.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalProjectedPolicy.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalRound.
Require PTree.Eq.Internal.FreeOmega.FiniteInternalRoundCoupling.
Require PTree.Eq.Internal.FreeOmega.KernelCompletion.
Require PTree.Eq.Internal.FreeOmega.KernelCongruence.
Require PTree.Eq.Internal.FreeOmega.KernelContinuity.
Require PTree.Eq.Internal.FreeOmega.KernelProjection.
Require PTree.Eq.Iter.
Require PTree.Eq.PEutt.
Require PTree.Eq.PStrong.
Require PTree.Eq.PStruct.
Require PTree.Eq.PTreeKernel.
Require PTree.Eq.PrimitiveStableHitting.
Require PTree.Eq.ProbabilisticTrace.
Require PTree.Eq.Relation.
Require PTree.Eq.RelationalHitting.
Require PTree.Eq.Shallow.
Require PTree.Eq.StableHittingComputation.
Require PTree.Eq.StableHittingRelation.
Require PTree.Eq.UnifiedFrontier.
Require PTree.Eq.WellFormedness.
Require PTree.Examples.BernoulliFactory.BernoulliFactory.
Require PTree.Examples.BernoulliFactory.BernoulliFactoryComposition.
Require PTree.Examples.BernoulliFactory.BernoulliFactoryProbability.
Require PTree.Examples.BernoulliFactory.OperationalBernoulliFactory.
Require PTree.Examples.BernoulliFactory.OperationalRationalBernoulli.
Require PTree.Examples.BernoulliFactory.OperationalVonNeumann.
Require PTree.Examples.BernoulliFactory.RationalBernoulli.
Require PTree.Examples.BernoulliFactory.RealBernoulliMathComp.
Require PTree.Examples.BernoulliFactory.RealBernoulliOracle.
Require PTree.Examples.BernoulliFactory.VonNeumannUnbounded.
Require PTree.Examples.InteractiveVonNeumann.InteractiveVonNeumannService.
Require PTree.Examples.MathCompPrograms.
Require PTree.Examples.MixedHeadProtocol.
Require PTree.Examples.RandomWalk.
Require PTree.Examples.RationalState.
Require PTree.Examples.StateCounter.
Require PTree.Examples.StateRewrite.
Require PTree.Execution.Backend.FiniteDistribution.
Require PTree.Execution.Backend.RationalTickets.
Require PTree.Execution.Backend.SubEnumQ.
Require PTree.Execution.Backend.UniformReplay.
Require PTree.Execution.ITreeFold.
Require PTree.Execution.Runner.
Require PTree.Execution.Validation.SubEnumQ.
Require PTree.Interp.Backend.SubEnumQ.
Require PTree.Interp.Exception.
Require PTree.Interp.ExceptionFacts.
Require PTree.Interp.FreeOmega.Atomic.
Require PTree.Interp.FreeOmega.Base.
Require PTree.Interp.FreeOmega.Cofinality.
Require PTree.Interp.FreeOmega.Guarded.
Require PTree.Interp.FreeOmega.HandlerCompletion.
Require PTree.Interp.FreeOmega.MDP.
Require PTree.Interp.FreeOmega.State.
Require PTree.Interp.FreeOmega.Translate.
Require PTree.Interp.FreeOmega.Unrestricted.
Require PTree.Interp.Guarded.
Require PTree.Interp.HandlerFacts.
Require PTree.Interp.HandlerMachine.
Require PTree.Interp.HandlerMachineAcceleration.
Require PTree.Interp.HandlerMachineScheduling.
Require PTree.Interp.HandlerRelation.
Require PTree.Interp.Kernel.
Require PTree.Interp.Preservation.
Require PTree.Interp.Reader.
Require PTree.Interp.RelationalPreservation.
Require PTree.Interp.Scheduling.
Require PTree.Interp.StandardFacts.
Require PTree.Interp.State.
Require PTree.Interp.StateFacts.
Require PTree.Interp.StateFold.
Require PTree.Interp.StateFoldFacts.
Require PTree.Interp.StateIter.
Require PTree.Interp.StateMachine.
Require PTree.Interp.StateMachineScheduling.
Require PTree.Interp.StatePreservation.
Require PTree.Interp.StateStrong.
Require PTree.Interp.Structural.
Require PTree.Interp.Unrestricted.
Require PTree.Interp.Writer.
Require PTree.PTree.
Require PTree.PTreeFacts.
Require PTree.Prob.Backend.Common.CountableCoupling.
Require PTree.Prob.Backend.Common.CountableRealTransport.
Require PTree.Prob.Backend.Common.CountableRelationalLimit.
Require PTree.Prob.Backend.Common.DomainTransport.
Require PTree.Prob.Backend.Common.FinSupp.
Require PTree.Prob.Backend.Common.FiniteAtoms.
Require PTree.Prob.Backend.Common.FiniteCapacityMatching.
Require PTree.Prob.Backend.Common.FiniteEnum.
Require PTree.Prob.Backend.Common.FiniteIndexedBind.
Require PTree.Prob.Backend.Common.FiniteListAlgebra.
Require PTree.Prob.Backend.Common.FiniteMatching.
Require PTree.Prob.Backend.Common.FinitePositions.
Require PTree.Prob.Backend.Common.FinitePresentation.
Require PTree.Prob.Backend.Common.FinitePruning.
Require PTree.Prob.Backend.Common.FiniteRationalTransport.
Require PTree.Prob.Backend.Common.FiniteRecordExtensionality.
Require PTree.Prob.Backend.Common.FiniteScalarMap.
Require PTree.Prob.Backend.Common.FiniteSubdist.
Require PTree.Prob.Backend.Common.FiniteSupport.
Require PTree.Prob.Backend.Common.RatGeometric.
Require PTree.Prob.Backend.Common.RealSubTypes.
Require PTree.Prob.Backend.Common.RealTransport.
Require PTree.Prob.Backend.EnumQ.Bind.
Require PTree.Prob.Backend.EnumQ.Coupling.
Require PTree.Prob.Backend.EnumQ.Disintegration.
Require PTree.Prob.Backend.EnumQ.FinitePresentation.
Require PTree.Prob.Backend.EnumQ.FiniteTransport.
Require PTree.Prob.Backend.EnumQ.FreeOmega.Coupling.
Require PTree.Prob.Backend.EnumQ.FreeOmega.MeasureAudit.
Require PTree.Prob.Backend.EnumQ.FreeOmega.NativeTransport.
Require PTree.Prob.Backend.EnumQ.FreeOmega.UpperContinuity.
Require PTree.Prob.Backend.EnumQ.FreeOmega.UpperCoupling.
Require PTree.Prob.Backend.EnumQ.FreeOmega.UpperExpectation.
Require PTree.Prob.Backend.EnumQ.FreeOmega.UpperObservation.
Require PTree.Prob.Backend.EnumQ.FreeOmega.UpperQuotient.
Require PTree.Prob.Backend.EnumQ.FreeOmega.UpperRelational.
Require PTree.Prob.Backend.EnumQ.FrontierLift.
Require PTree.Prob.Backend.EnumQ.IndexedCoupling.
Require PTree.Prob.Backend.EnumQ.Iteration.
Require PTree.Prob.Backend.EnumQ.Map.
Require PTree.Prob.Backend.EnumQ.Measure.
Require PTree.Prob.Backend.EnumQ.Representation.
Require PTree.Prob.Backend.EnumQ.SemanticCoupling.
Require PTree.Prob.Backend.EnumQ.Support.
Require PTree.Prob.Backend.MathComp.BindLaws.
Require PTree.Prob.Backend.MathComp.BindOrder.
Require PTree.Prob.Backend.MathComp.Coupling.
Require PTree.Prob.Backend.MathComp.Kernel.
Require PTree.Prob.Backend.MathComp.Measure.
Require PTree.Prob.Backend.MathComp.NativeLaws.
Require PTree.Prob.Backend.MathComp.OmegaLaws.
Require PTree.Prob.Backend.MathComp.OrderLaws.
Require PTree.Prob.Backend.MathComp.RelationalClosure.
Require PTree.Prob.Backend.MathComp.Retry.
Require PTree.Prob.Backend.SubEnumQ.Domain.
Require PTree.Prob.Backend.SubEnumQ.Expectation.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.Admissibility.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.CodedJoint.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.CountableSupport.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.CouplingSoundness.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.Disintegration.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.DomainSoundness.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.EquivalenceJoint.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.GenericValidation.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.JointSoundness.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.NativeCoupling.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.NativeTransport.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.QuotientSoundness.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.Recovery.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.RelationalValidation.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.Total.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.UpperContinuity.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.UpperCoupling.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.UpperExpectation.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.UpperObservation.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.UpperQuotient.
Require PTree.Prob.Backend.SubEnumQ.FreeOmega.UpperRelational.
Require PTree.Prob.Backend.SubEnumQ.Measure.
Require PTree.Prob.Backend.SubEnumQ.Representation.
Require PTree.Prob.Backend.SubEnumR.Coupling.
Require PTree.Prob.Backend.SubEnumR.Domain.
Require PTree.Prob.Backend.SubEnumR.FreeOmega.CountableSupport.
Require PTree.Prob.Backend.SubEnumR.FreeOmega.JointRealization.
Require PTree.Prob.Backend.SubEnumR.FreeOmega.RelationalValidation.
Require PTree.Prob.Backend.SubEnumR.FreeOmega.Validation.
Require PTree.Prob.Backend.SubEnumR.Measure.
Require PTree.Prob.Backend.SubEnumR.Omega.
Require PTree.Prob.Backend.SubEnumR.RationalEmbedding.
Require PTree.Prob.Backend.SubEnumR.Representation.
Require PTree.Prob.Domain.Atomic.
Require PTree.Prob.Domain.Countable.
Require PTree.Prob.Domain.CountableTransport.
Require PTree.Prob.Domain.Coupling.
Require PTree.Prob.Domain.Expectation.
Require PTree.Prob.Domain.Matrix.
Require PTree.Prob.Domain.MeasureModel.
Require PTree.Prob.Domain.RelationalLimit.
Require PTree.Prob.Domain.Series.
Require PTree.Prob.FreeOmega.Approximation.
Require PTree.Prob.FreeOmega.BindOrder.
Require PTree.Prob.FreeOmega.Coupling.
Require PTree.Prob.FreeOmega.Definition.
Require PTree.Prob.FreeOmega.JointExtension.
Require PTree.Prob.FreeOmega.Measure.
Require PTree.Prob.FreeOmega.Native.
Require PTree.Prob.FreeOmega.NativeCoupling.
Require PTree.Prob.FreeOmega.Observation.
Require PTree.Prob.FreeOmega.Quotient.
Require PTree.Prob.FreeOmega.Recovery.
Require PTree.Prob.FreeOmega.RelationalLimit.
Require PTree.Prob.FreeOmega.StructuralMeasure.
Require PTree.Prob.FreeOmega.Support.
Require PTree.Prob.FreeOmega.SupportLift.
Require PTree.Prob.FreeOmega.Validation.Continuity.
Require PTree.Prob.FreeOmega.Validation.Expectation.
Require PTree.Prob.FreeOmega.Validation.Observation.
Require PTree.Prob.FreeOmega.Validation.Quotient.
Require PTree.Prob.FreeOmega.Validation.Relational.
Require PTree.Prob.Interface.AE.
Require PTree.Prob.Interface.BindOrder.
Require PTree.Prob.Interface.Coupling.
Require PTree.Prob.Interface.FrontierLift.
Require PTree.Prob.Interface.Iteration.
Require PTree.Prob.Interface.Measure.
Require PTree.Prob.Interface.Mixed.
Require PTree.Prob.Interface.Omega.
Require PTree.Prob.Interface.RelationalClosure.
Require PTree.Prob.Interface.RelationalLimit.
Require PTree.Prob.Interface.SemanticCoupling.
Require PTree.Prob.Interface.Subprobability.
Require PTree.Prob.Legacy.Discrete.
Require PTree.Prob.Legacy.Monad.
Require PTree.Prob.Legacy.MonadList.
Require PTree.Prob.Legacy.RatSubTypes.
Require PTree.Prob.Legacy.RationalDiscrete.
Require PTree.Prob.Legacy.RelLift.
Require PTree.Regression.Backend.BackendCapabilities.
Require PTree.Regression.Backend.CouplingRealization.
Require PTree.Regression.Backend.EnumQMeasureRegression.
Require PTree.Regression.Backend.ExtendedEnumQ.
Require PTree.Regression.Backend.FiniteBackendConsolidation.
Require PTree.Regression.Backend.FiniteSupport.
Require PTree.Regression.Backend.FreeOmegaEscapingMass.
Require PTree.Regression.Backend.FreeOmegaLimitSafety.
Require PTree.Regression.Backend.FreeOmegaUpperContracts.
Require PTree.Regression.Backend.MathCompOmega.
Require PTree.Regression.Backend.MathCompOrder.
Require PTree.Regression.Backend.NativeReflection.
Require PTree.Regression.Backend.RationalFiniteAlgebra.
Require PTree.Regression.Backend.RationalPositions.
Require PTree.Regression.Backend.RationalPresentation.
Require PTree.Regression.Backend.RationalPruning.
Require PTree.Regression.Backend.RationalReplay.
Require PTree.Regression.Backend.RationalRepresentationMigration.
Require PTree.Regression.Backend.SubEnumQRegression.
Require PTree.Regression.Backend.SubEnumR.
Require PTree.Regression.Backend.SubEnumRBehavior.
Require PTree.Regression.Backend.SubEnumRRelational.
Require PTree.Regression.Backend.SubEnumRShared.
Require PTree.Regression.Backend.UnifiedFrontierEnumQ.
Require PTree.Regression.Execution.FiniteDistribution.
Require PTree.Regression.Execution.RationalTickets.
Require PTree.Regression.Fixtures.FreeOmegaSamples.
Require PTree.Regression.Infrastructure.ArchitectureBoundaries.
Require PTree.Regression.Infrastructure.CanonicalBehavior.
Require PTree.Regression.Infrastructure.CanonicalBehaviorNativeFirst.
Require PTree.Regression.Infrastructure.CanonicalBehaviorStructuralFirst.
Require PTree.Regression.Infrastructure.CapabilityBoundaries.
Require PTree.Regression.Infrastructure.CorrelatedInternalRounds.
Require PTree.Regression.Infrastructure.CostedRounds.
Require PTree.Regression.Infrastructure.CouplingReferences.
Require PTree.Regression.Infrastructure.Execution.
Require PTree.Regression.Infrastructure.FiniteInternalNative.
Require PTree.Regression.Infrastructure.FiniteInternalPlan.
Require PTree.Regression.Infrastructure.FiniteInternalRound.
Require PTree.Regression.Infrastructure.HiddenRandomState.
Require PTree.Regression.Infrastructure.KernelCompletion.
Require PTree.Regression.Infrastructure.KernelCongruence.
Require PTree.Regression.Infrastructure.KernelContinuity.
Require PTree.Regression.Infrastructure.MathCompUniverse.
Require PTree.Regression.Infrastructure.NativeRecovery.
Require PTree.Regression.Infrastructure.PairedFiniteCompression.
Require PTree.Regression.Infrastructure.PublicBehavior.
Require PTree.Regression.Infrastructure.PublicHandlers.
Require PTree.Regression.Infrastructure.ResidualFinite.
Require PTree.Regression.Infrastructure.ResidualJointCoinduction.
Require PTree.Regression.Infrastructure.ResidualTransport.
Require PTree.Regression.Infrastructure.StateIteration.
Require PTree.Regression.Infrastructure.StructuralRegistry.
Require PTree.Regression.Infrastructure.UniverseSeparatedPTree.
Require PTree.Regression.Probability.ConditionalResampling.
Require PTree.Regression.Probability.CorrelatedSampleAlgebra.
Require PTree.Regression.Probability.CountableCoupling.
Require PTree.Regression.Probability.EnumQDisintegration.
Require PTree.Regression.Probability.FiniteRepresentation.
Require PTree.Regression.Probability.FiniteTransport.
Require PTree.Regression.Probability.FreeOmegaDomain.
Require PTree.Regression.Probability.FreeOmegaSoundness.
Require PTree.Regression.Probability.GenericFreeOmegaValidation.
Require PTree.Regression.Probability.GenericQuotientValidation.
Require PTree.Regression.Probability.IrrationalHitting.
Require PTree.Regression.Probability.OmegaVal.
Require PTree.Regression.Probability.OmegaValMeasure.
Require PTree.Regression.Probability.RealTransport.
Require PTree.Regression.Probability.RelationalLimit.
Require PTree.Regression.Probability.StableHittingDomain.
Require PTree.Regression.Probability.SubEnumRJointRealization.
Require PTree.Regression.Semantics.AtomicInterp.
Require PTree.Regression.Semantics.CanonicalPartialDivergence.
Require PTree.Regression.Semantics.GenericAlgebra.
Require PTree.Regression.Semantics.GenericBind.
Require PTree.Regression.Semantics.GenericConsumers.
Require PTree.Regression.Semantics.GuardedInterp.
Require PTree.Regression.Semantics.HandlerCalculus.
Require PTree.Regression.Semantics.HeadTransition.
Require PTree.Regression.Semantics.InterpExposure.
Require PTree.Regression.Semantics.LabelledMDP.
Require PTree.Regression.Semantics.MDPCoincidence.
Require PTree.Regression.Semantics.MDPEmbedding.
Require PTree.Regression.Semantics.MDPFragment.
Require PTree.Regression.Semantics.MDPInterp.
Require PTree.Regression.Semantics.OperationalPTSExamples.
Require PTree.Regression.Semantics.PEuttAlgebra.
Require PTree.Regression.Semantics.ProbabilisticRelationHierarchy.
Require PTree.Regression.Semantics.PublicSemanticFacade.
Require PTree.Regression.Semantics.RelationalConsumers.
Require PTree.Regression.Semantics.StableHittingComputation.
Require PTree.Regression.Semantics.StandardEffects.
Require PTree.Regression.Semantics.StateFold.
Require PTree.Regression.Semantics.StatePreservation.
Require PTree.Regression.Semantics.TreeTransition.
Require PTree.Regression.Semantics.TreeTransitionBisim.
Require PTree.Regression.Semantics.TreeTransitionSoundness.
Require PTree.Regression.Semantics.TreeTransitionStrictness.
Require PTree.Regression.Semantics.UnrestrictedInterp.
Require PTree.Semantics.
Require PTree.Semantics.Backend.MDPEmbeddingSubEnumQ.
Require PTree.Semantics.FreeOmega.MDPCoincidenceFreeOmega.
Require PTree.Semantics.HeadTransition.
Require PTree.Semantics.MDPCoincidence.
Require PTree.Semantics.MDPEmbedding.
Require PTree.Semantics.MDPFragment.
Require PTree.Semantics.TreeTransition.
Require PTree.Semantics.TreeTransitionBisim.
Require PTree.Semantics.TreeTransitionSoundness.
