(** Role: Low-universe observation and quotient-closed denotation; not chosen representatives. *)
Set Warnings "-notation-overridden".
Set Warnings "-ambiguous-paths".
Set Universe Polymorphism.

Require Import FunctionalExtensionality.
From Coq.Program Require Import Equality.
Require Import Morphisms Arith.

From PTree.Prob.Interface Require Import Measure Omega.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Require Import PTree.Prob.FreeOmega.Definition PTree.Prob.FreeOmega.Approximation.


(** Relational interpretation into a low-universe observable distribution.
    It is relational because an abstract omega interface specifies limits by
    [sem_lub] rather than by a choice function.  A formal [FOLub] is observed
    only along an increasing raw chain.  Mere convergence of its images
    is insufficient: it permits escaping mass under subsequent bind
    continuity (see Regression/Backend/FreeOmegaEscapingMass). *)
Section FreeOmegaObservationDefinition.
Universes node node_rep frontier.
(** Observations land in the native node universe; the observed carrier
    may live higher.  Keep this boundary explicit even for Boolean
    observations, whose universe must not be minimized independently. *)
Context {MN : Type@{node} -> Type@{node_rep}}
    `{NI : SemanticMeasure MN}
    `{NO : @SemanticOmega MN NI}
    {A : Type@{frontier}} {O : Type@{node}}.
Polymorphic Inductive free_omega_observes (obs : A -> O) : FreeOmega MN A -> MN O -> Prop :=
  | FOOObserveRet x :
      free_omega_observes obs (FORet x) (sem_ret (obs x))
  | FOOObserveZero :
      free_omega_observes obs FOZero sem_zero
  | FOOObserveSample {X} (mu : MN X) k (front : X -> MN O) :
      (forall x, free_omega_observes obs (k x) (front x)) ->
      free_omega_observes obs (FOSample mu k) (sem_bind mu front)
  | FOOObserveLub chain outs out :
      (forall n, free_omega_observes obs (chain n) (outs n)) ->
      sem_lub outs out ->
      (forall n, free_omega_approx eq (chain n) (chain (S n))) ->
      free_omega_observes obs (FOLub chain) out.
End FreeOmegaObservationDefinition.

(** Quotient-closed observable meaning.  The inductive observation relation
    records a concrete representative generated by the FreeOmega syntax;
    clients should normally reason through [free_omega_denotes], because a
    measure backend may identify several such representatives by [sem_eq]. *)
Definition free_omega_denotes {MN}
    `{NI : SemanticMeasure MN}
    `{NO : @SemanticOmega MN NI} {A O}
    (obs : A -> O) (mu : FreeOmega MN A) (out : MN O) : Prop :=
  exists represented,
    free_omega_observes obs mu represented /\ sem_eq represented out.

Section FreeOmegaDenotationBasics.
Context {MN : Type -> Type}
  `{NI : SemanticMeasure MN}
  `{NC : @SemanticMeasureCoreLaws MN NI}
  `{NO : @SemanticOmega MN NI}.

Lemma free_omega_observes_denotes {A O} (obs : A -> O)
    (mu : FreeOmega MN A) out :
  free_omega_observes obs mu out -> free_omega_denotes obs mu out.
Proof.
  intro Hobs. exists out. split; [exact Hobs|apply sem_eq_refl].
Qed.

Lemma free_omega_denotes_proper {A O} (obs : A -> O)
    (mu : FreeOmega MN A) out1 out2 :
  free_omega_denotes obs mu out1 -> sem_eq out1 out2 ->
  free_omega_denotes obs mu out2.
Proof.
  intros [represented [Hobs Heq1]] Heq2.
  exists represented. split; [exact Hobs|].
  eapply sem_eq_trans; eassumption.
Qed.

End FreeOmegaDenotationBasics.

(** These two capabilities isolate the analytic content needed to compose
    low-level observations of nested unbounded programs.  They are not
    consequences of the raw [free_omega_observes] constructors: bind needs
    monotone continuity, while lub needs a coherent choice of equivalent
    representatives.  Quotient measure models normally satisfy both;
    concrete list models must prove them extensionally. *)
Polymorphic Class FreeOmegaDenotationBindLaws {MN}
    `{NI : SemanticMeasure MN}
    `{NO : @SemanticOmega MN NI} := {
  free_omega_denotes_bind : forall {A B OA OB}
      (obsA : A -> OA) (obsB : B -> OB)
      (mu : FreeOmega MN A) (out : MN OA)
      (k : A -> FreeOmega MN B) (front : OA -> MN OB),
    free_omega_denotes obsA mu out ->
    (forall x, free_omega_denotes obsB (k x) (front (obsA x))) ->
    free_omega_denotes obsB (free_omega_bind mu k)
      (sem_bind out front)
}.

Polymorphic Class FreeOmegaDenotationOmegaLaws {MN}
    `{NI : SemanticMeasure MN}
    `{NO : @SemanticOmega MN NI} := {
  free_omega_denotes_lub : forall {A O} (obs : A -> O)
      (chain : nat -> FreeOmega MN A) (outs : nat -> MN O) out,
    (forall n, free_omega_denotes obs (chain n) (outs n)) ->
    sem_lub outs out ->
    (forall n, free_omega_approx eq (chain n) (chain (S n))) ->
    free_omega_denotes obs (FOLub chain) out
}.

Lemma free_omega_observes_bind_ret {MN}
    `{NI : SemanticMeasure MN}
    `{NO : @SemanticOmega MN NI}
    {A B O} (obsA : A -> O) (obsB : B -> O) (f : A -> B)
    (mu : FreeOmega MN A) (out : MN O) :
  free_omega_observes obsA mu out ->
  (forall x, obsB (f x) = obsA x) ->
  free_omega_observes obsB
    (free_omega_bind mu (fun x => FORet (f x))) out.
Proof.
  intros Hobs Hf. induction Hobs; cbn.
  - rewrite <- Hf. constructor.
  - constructor.
  - eapply FOOObserveSample. exact H0.
  - eapply FOOObserveLub; eauto.
    intro n. eapply free_omega_approx_bind; [apply H2|].
    intros x y ->. apply FOApproxRet. reflexivity.
Qed.

Section FreeOmegaObservationLaws.
Context {MN : Type -> Type}
  `{NI : SemanticMeasure MN}
  `{NC : @SemanticMeasureCoreLaws MN NI}
  `{NB : @SemanticMeasureBindLaws MN NI}
  `{NO : @SemanticOmega MN NI}
  `{NOL : @SemanticOmegaLaws MN NI NO}.

(** Observation is relational only because [sem_lub] need not choose a
    concrete representative.  Once the node backend supplies extensional lub
    uniqueness, the denoted low-universe distribution is deterministic up to
    [sem_eq]. *)
Lemma free_omega_observes_unique {A O} (obs : A -> O)
    (mu : FreeOmega MN A) out1 out2 :
  free_omega_observes obs mu out1 ->
  free_omega_observes obs mu out2 ->
  sem_eq out1 out2.
Proof.
  intros H1. revert out2. induction H1; intros out2 Hother;
    dependent destruction Hother.
  - apply sem_eq_refl.
  - apply sem_eq_refl.
  - apply sem_bind_ae_proper.
    eapply sem_ae_mono; [|apply sem_ae_true].
    intros x _. exact (H0 x _ (H1 x)).
  - eapply sem_lub_proper.
    + intros n. exact (H0 n _ (H3 n)).
    + exact H1.
    + exact H4.
Qed.

End FreeOmegaObservationLaws.
