(** Raw finite weighted-list algebra. Multiplication is an ordinary function,
    not a new scalar subtype or probability capability. Algebraic laws are
    explicit lemma premises; checked numeric operations specialize them. *)
Set Warnings "-notation-overridden,-ambiguous-paths".
Set Universe Polymorphism.
Local Unset Universe Minimization ToSet.
From Coq Require Import List PeanoNat Arith.
From mathcomp Require Import ssreflect ssrbool ssrfun ssrnat seq ssralg ssrnum order.
From PTree.Prob.Backend.Common Require Import FiniteEnum.
Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.
Import GRing.Theory Num.Theory Order.Theory.
Local Open Scope ring_scope.

Section RawAlgebra.
Context {W : Type} (mul : W -> W -> W).

Fixpoint finite_scale_with {A : Type} (p : W) (mu : list (W * A)) : list (W * A) :=
  match mu with
  | [::] => [::]
  | (q,x)::tl => (mul p q,x)::finite_scale_with p tl
  end.

Definition finite_bind_with {A B : Type} (mu : list (W * A)) (k : A -> list (W * B)) :=
  foldr (fun '(p,x) tl => finite_scale_with p (k x) ++ tl) [::] mu.

Lemma finite_bind_with_ext {A B} (mu : list (W*A))
    (k h : A -> list (W*B)) :
  (forall x, k x = h x) -> finite_bind_with mu k = finite_bind_with mu h.
Proof. move=> H; by elim: mu=> [|[p x] mu IH] //=; rewrite H IH. Qed.

Lemma finite_scale_with_map {A} p (mu : list (W * A)) :
  finite_scale_with p mu = List.map (fun px => (mul p px.1, px.2)) mu.
Proof. by elim: mu=> [|[q x] tl IH] //=; rewrite IH. Qed.

Lemma finite_scale_with_app {A} p (mu nu : list (W * A)) :
  finite_scale_with p (mu ++ nu) = finite_scale_with p mu ++ finite_scale_with p nu.
Proof. by elim: mu=> [|[q x] tl IH] //=; rewrite IH. Qed.

Lemma finite_scale_with_comp {A} p q (mu : list (W * A)) :
  (forall a b c, mul a (mul b c) = mul (mul a b) c) ->
  finite_scale_with p (finite_scale_with q mu) = finite_scale_with (mul p q) mu.
Proof. move=> Hassoc; by elim: mu=> [|[r x] tl IH] //=; rewrite Hassoc IH. Qed.

Lemma finite_bind_with_app {A B} (mu nu : list (W * A)) (k : A -> list (W * B)) :
  finite_bind_with (mu ++ nu) k = finite_bind_with mu k ++ finite_bind_with nu k.
Proof. by elim: mu=> [|[p x] tl IH] //=; rewrite IH catA. Qed.

Lemma finite_scale_with_bind {A B} p (mu : list (W * A)) (k : A -> list (W * B)) :
  (forall a b c, mul a (mul b c) = mul (mul a b) c) ->
  (forall a b, mul a b = mul b a) ->
  finite_scale_with p (finite_bind_with mu k) =
  finite_bind_with mu (fun x => finite_scale_with p (k x)).
Proof.
  move=> Hassoc Hcomm; elim: mu=> [|[q x] tl IH] //=.
  rewrite finite_scale_with_app IH !finite_scale_with_comp //.
  by rewrite (Hcomm p q).
Qed.

Lemma finite_bind_with_scale {A B} p (mu : list (W * A)) (k : A -> list (W * B)) :
  (forall a b c, mul a (mul b c) = mul (mul a b) c) ->
  finite_bind_with (finite_scale_with p mu) k = finite_scale_with p (finite_bind_with mu k).
Proof.
  move=> Hassoc; elim: mu=> [|[q x] tl IH] //=.
  by rewrite finite_scale_with_app finite_scale_with_comp // IH.
Qed.

Lemma finite_bind_with_assoc {A B C} (mu : list (W * A))
    (k : A -> list (W * B)) (h : B -> list (W * C)) :
  (forall a b c, mul a (mul b c) = mul (mul a b) c) ->
  finite_bind_with (finite_bind_with mu k) h =
  finite_bind_with mu (fun x => finite_bind_with (k x) h).
Proof.
  move=> Hassoc; elim: mu=> [|[p x] tl IH] //=.
  by rewrite finite_bind_with_app finite_bind_with_scale // IH.
Qed.

Lemma finite_bind_with_left_unit {A B} one (x : A) (k : A -> list (W * B)) :
  (forall p, mul one p = p) -> finite_bind_with [:: (one,x)] k = k x.
Proof.
  move=> H; rewrite /finite_bind_with /= cats0 finite_scale_with_map.
  elim: (k x)=> [|[p y] tl IH] //=; by rewrite H IH.
Qed.

Lemma finite_bind_with_right_unit {A} one (mu : list (W * A)) :
  (forall p, mul p one = p) -> finite_bind_with mu (fun x => [:: (one,x)]) = mu.
Proof. move=> H; by elim: mu=> [|[p x] tl IH] //=; rewrite H IH. Qed.

Lemma finite_scale_with_length {A} p (mu : list (W * A)) :
  size (finite_scale_with p mu) = size mu.
Proof. by elim: mu=> [|[q x] tl IH] //=; rewrite IH. Qed.
(** Starting position of the continuation block generated by the [i]-th
    entry of an outer enumeration. *)
Fixpoint finite_bind_offset {A B} (mu : list (W * A)) (k : A -> list (W * B))
    (i : nat) : nat :=
  match mu, i with
  | [::], _ => 0
  | _, 0 => 0
  | (_, a) :: tl, i'.+1 => (size (k a) + finite_bind_offset tl k i')%N
  end.

Lemma finite_scale_with_nth {A} p (mu : list (W * A)) i q a :
  nth_error mu i = Some (q, a) ->
  nth_error (finite_scale_with p mu) i = Some (mul p q, a).
Proof.
  elim: mu i=> [|[r x] mu IH] [|i] //=.
  - by move=> H; inversion H; subst.
  - exact: IH.
Qed.

Lemma finite_nth_app_right {A} (xs ys : seq A) i y :
  nth_error ys i = Some y ->
  nth_error (xs ++ ys) (size xs + i)%N = Some y.
Proof.
  by elim: xs=> [|x xs IH] //=.
Qed.

Lemma finite_nth_app_left {A} (xs ys : seq A) i x :
  nth_error xs i = Some x ->
  nth_error (xs ++ ys) i = Some x.
Proof.
  elim: xs i=> [|y xs IH] [|i] //=.
  exact: IH.
Qed.

Lemma finite_scale_with_nth_inv {A} p (mu : list (W * A)) i w a :
  nth_error (finite_scale_with p mu) i = Some (w, a) ->
  exists q, nth_error mu i = Some (q, a) /\ w = mul p q.
Proof.
  elim: mu i=> [|[q b] mu IH] [|i] //=.
  - move=> H. inversion H; subst. by exists q.
  - exact: IH.
Qed.

Lemma finite_nth_app_inv {A} (xs ys : seq A) n z :
  nth_error (xs ++ ys) n = Some z ->
  (Peano.lt n (size xs) /\ nth_error xs n = Some z) \/
  exists j, n = (size xs + j)%N /\ nth_error ys j = Some z.
Proof.
  move=> H.
  destruct (PeanoNat.Nat.lt_ge_cases n (size xs)) as [Hlt|Hge].
  - left. split=> //.
    rewrite -(@nth_error_app1 A xs ys n Hlt). exact H.
  - right. exists (n - size xs)%N. split.
    + change (n = size xs + (n - size xs))%coq_nat.
      rewrite Nat.add_comm. symmetry. apply Nat.sub_add. exact Hge.
    + rewrite -(@nth_error_app2 A xs ys n Hge). exact H.
Qed.

(** Exact position and weight of an entry after flattening a finite bind. *)
Lemma finite_bind_with_nth {A B} (mu : list (W * A)) (k : A -> list (W * B))
    i j p a q b :
  nth_error mu i = Some (p, a) ->
  nth_error (k a) j = Some (q, b) ->
  nth_error (finite_bind_with mu k) (finite_bind_offset mu k i + j)%N =
    Some (mul p q, b).
Proof.
  elim: mu i p a=> [|[r x] mu IH] [|i] p a //=.
  - move=> Houter Hinner. inversion Houter; subst r x.
    apply finite_nth_app_left.
    apply finite_scale_with_nth. exact Hinner.
  - move=> Houter Hinner.
    have Htail := IH i p a Houter Hinner.
    have Happ := @finite_nth_app_right (W * B)
      (finite_scale_with r (k x)) (finite_bind_with mu k)
      (finite_bind_offset mu k i + j)%N (mul p q, b) Htail.
    rewrite finite_scale_with_length in Happ.
    replace (size (k x) + finite_bind_offset mu k i + j)%N
      with (size (k x) + (finite_bind_offset mu k i + j))%N.
    - exact Happ.
    - apply PeanoNat.Nat.add_assoc.
Qed.

(** Every successful position in a flattened bind comes from an outer entry
    and one entry of its continuation block. *)
Lemma finite_bind_with_nth_inv {A B} (mu : list (W * A)) (k : A -> list (W * B))
    n w b :
  nth_error (finite_bind_with mu k) n = Some (w, b) ->
  exists i j p a q,
    nth_error mu i = Some (p, a) /\
    nth_error (k a) j = Some (q, b) /\
    n = (finite_bind_offset mu k i + j)%N /\ w = mul p q.
Proof.
  elim: mu n=> [|[p a] mu IH] n Hnth.
  - destruct n; cbn in Hnth; discriminate.
  - cbn in Hnth.
    move: (finite_nth_app_inv Hnth)=> [[Hlt Hhead]|[n' [Hn Htail]]].
    + move: (finite_scale_with_nth_inv Hhead)=> [q [Hq ->]].
      exists 0%N, n, p, a, q. repeat split=> //.
    + rewrite finite_scale_with_length in Hn.
      move: (IH n' Htail)=> [i [j [r [x [q [Hi [Hj [Hoff Hw]]]]]]]].
      exists i.+1, j, r, x, q. repeat split=> //.
      rewrite Hn Hoff /=.
      rewrite addnA. reflexivity.
Qed.
End RawAlgebra.

Lemma finite_scale_with_scalar_map {W V A} (mul : W -> W -> W)
    (mul' : V -> V -> V) (f : W -> V) p (mu : list (W * A)) :
  (forall p q, f (mul p q) = mul' (f p) (f q)) ->
  List.map (fun px => (f px.1, px.2)) (finite_scale_with mul p mu) =
  finite_scale_with mul' (f p) (List.map (fun px => (f px.1, px.2)) mu).
Proof. move=> H; by elim: mu=> [|[q x] tl IH] //=; rewrite H IH. Qed.

Lemma finite_bind_with_scalar_map {W V A B} (mul : W -> W -> W)
    (mul' : V -> V -> V) (f : W -> V) (mu : list (W * A)) (k : A -> list (W * B)) :
  (forall p q, f (mul p q) = mul' (f p) (f q)) ->
  List.map (fun px => (f px.1, px.2)) (finite_bind_with mul mu k) =
  finite_bind_with mul' (List.map (fun px => (f px.1, px.2)) mu)
    (fun x => List.map (fun px => (f px.1, px.2)) (k x)).
Proof.
  move=> H; elim: mu=> [|[p x] tl IH] //=.
  by rewrite List.map_app (finite_scale_with_scalar_map (mul' := mul') _ _ H) IH.
Qed.

Section CheckedConnection.
Variable R : numDomainType.
Lemma finite_scale_with_weight_map {A} (p : R) (mu : list (R * A)) :
  finite_scale_with (fun x y => x * y) p mu = finite_weight_map p mu.
Proof. exact: finite_scale_with_map. Qed.
Lemma finite_bind_with_numeric {A B} (mu : list (R * A)) (k : A -> list (R * B)) :
  finite_bind_with (fun x y => x * y) mu k = finite_bind mu k.
Proof. by elim: mu=> [|[p x] tl IH] //=; rewrite finite_scale_with_weight_map IH. Qed.
Lemma finite_bind_ext {A B} (mu : list (R*A)) (k h : A -> list (R*B)) :
  (forall x, k x = h x) -> finite_bind mu k = finite_bind mu h.
Proof. move=> H; by elim: mu=> [|[p x] tl IH] //=; rewrite H IH. Qed.
Lemma finite_bind_app {A B} (mu nu : list (R*A)) (k : A -> list (R*B)) :
  finite_bind (mu++nu) k = finite_bind mu k ++ finite_bind nu k.
Proof. exact: List.flat_map_app. Qed.
Lemma finite_weight_map_comp {A} (p q : R) (mu : list (R*A)) :
  finite_weight_map p (finite_weight_map q mu) = finite_weight_map (p*q) mu.
Proof. by elim: mu=> [|[r x] tl IH] //=; rewrite mulrA IH. Qed.
Lemma finite_bind_scale {A B} (p : R) (mu : list (R*A)) (k : A -> list (R*B)) :
  finite_bind (finite_weight_map p mu) k = finite_weight_map p (finite_bind mu k).
Proof.
  rewrite -!finite_bind_with_numeric -!finite_scale_with_weight_map.
  apply finite_bind_with_scale; exact: mulrA.
Qed.
Lemma finite_bind_assoc {A B C} (mu : list (R*A))
    (k : A -> list (R*B)) (h : B -> list (R*C)) :
  finite_bind (finite_bind mu k) h = finite_bind mu (fun x => finite_bind (k x) h).
Proof.
  by elim: mu=> [|[p x] tl IH] //=; rewrite finite_bind_app finite_bind_scale IH.
Qed.
Lemma finite_expect_swap {A B} (mu : list (R*A)) (nu : list (R*B)) f :
  finite_expect (fun x => finite_expect (f x) nu) mu =
  finite_expect (fun y => finite_expect (fun x => f x y) mu) nu.
Proof.
  elim: mu=> [|[p x] tl IH] /=.
  - symmetry; exact: finite_expect_zero.
  - by rewrite finite_expect_add finite_expect_scale IH.
Qed.
End CheckedConnection.
