#!/usr/bin/env python3
"""Query compiled endpoint types and logical assumptions, without editing files.

Run dune build first. This selected baseline is NOT a full public-theorem
audit and does NOT prove mathematical minimality. Class names come from
elaborated types, never from a source Section's Context block.
"""
import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/CAPABILITY_BASELINE.md"
GROUPS = {
    "PTree.Eq.PEutt": ["peutt", "peutt_bind"],
    "PTree.Eq.FreeOmega.Algebra": ["peutt_bind_assoc"],
    "PTree.Eq.FreeOmega.Iter": ["peutt_iter_rel", "peutt_iter_behavioral_rel",
                               "peutt_iter_eventful_of_generator_closed"],
    "PTree.Eq.FreeOmega.GuardedInterp": ["guarded_handler", "guarded_handler_of_hitting",
        "guarded_handler_vis_fusion", "peutt_interp_guarded", "peutt_interp_guarded_Proper"],
    "PTree.Semantics.AtomicInterp": ["atomic_handler", "atomic_handler_guarded",
                                     "tree_trans_bisim_interp_atomic"],
    "PTree.Semantics.MDPCoincidenceFreeOmega": ["free_mdp_state_peutt_tree_trans_iff"],
    "PTree.Semantics.MDPInterp": ["mdp_handler", "mdp_state_interp",
        "mdp_interp_peutt_tree_trans_iff", "mdp_guarded_interp_tree_trans",
        "mdp_head_atomic", "atomic_handler_mdp", "mdp_state_interp_atomic"],
    "PTree.Prob.FreeOmegaTotalSubEnum": ["subenum_free_omega_total_map"],
    "PTree.Semantics.MDPInterpSubEnum": ["subenum_atomic_handler_mdp",
                                       "subenum_mdp_state_interp_atomic"],
}
ENDPOINTS = [module + "." + name for module, names in GROUPS.items() for name in names]


def marker(name):
    return f'Goal True. idtac "{name}". Abort.'


def clean(block):
    # A marker's Goal command reports a goal before idtac prints the delimiter.
    block = re.sub(r"\n\d+ goals?\b[\s\S]*$", "", block)
    block = re.sub(r"^\[?Fetching opaque proofs[^\n]*\n?", "", block, flags=re.M)
    return "\n".join(line.rstrip() for line in block.strip().splitlines())


def query():
    commands = ["Require " + module + "." for module in GROUPS]
    commands += ["Set Printing Width 100.", "Set Printing Depth 1000.", "Set Printing Implicit."]
    for i, endpoint in enumerate(ENDPOINTS):
        commands += [marker(f"AUDIT_TYPE_{i}"), "Check @" + endpoint + ".",
                     marker(f"AUDIT_AXIOMS_{i}"), "Print Assumptions " + endpoint + ".",
                     marker(f"AUDIT_END_{i}")]
    result = subprocess.run(
        ["opam", "exec", "--", "coqtop", "-quiet", "-R", "_build/default/theories", "PTree"],
        input="\n".join(commands) + "\n", text=True, capture_output=True, cwd=ROOT)
    if result.returncode or re.search(r"\bError:", result.stderr + result.stdout):
        raise SystemExit("Coq endpoint audit failed:\n" + result.stderr + result.stdout)
    answers = []
    for i, endpoint in enumerate(ENDPOINTS):
        pattern = rf"AUDIT_TYPE_{i}\n(.*?)AUDIT_AXIOMS_{i}\n(.*?)AUDIT_END_{i}\n"
        match = re.search(pattern, result.stdout, re.S)
        if not match:
            raise SystemExit("Missing audit markers for " + endpoint)
        typ, assumptions = map(clean, match.groups())
        if not re.search(r"Axioms:|Closed under the global context", assumptions):
            raise SystemExit("Unrecognized assumption output for " + endpoint + ": " + assumptions)
        answers.append((endpoint, typ, assumptions))
    return answers


def report(answers):
    rows = ["# Elaborated capability and logical-assumption baseline", "",
        "Generated by `python3 tools/audit_capabilities.py` after `opam exec -- dune build`. "
        "Use `--check` to compare with this baseline. Queries run together against the compiled library.", "",
        f"Scope: **{len(answers)} selected definitions/helpers/endpoints**. This is a pre-cleanup "
        "signature baseline, not an audit of every public theorem or a proof that these capabilities "
        "are mathematically minimal. No theorem statements or proofs were changed to obtain it.", "",
        "The table lists operation and law class names occurring in the elaborated type "
        "(`Check @endpoint`, with implicit arguments printed). Full types below retain the "
        "carrier assignments, relation parameters and local semantic premises. Repeated class "
        "names on different carriers are collapsed **only in the summary**, not in the full type.", "",
        "`Print Assumptions` is a separate logical audit: it does not enumerate theorem "
        "parameters such as backend laws or a handler contract. Unused Section variables "
        "already dropped by Rocq are absent here; unused source Context cleanup is a distinct task. "
        "For concrete SubEnum endpoints, `none` in the class columns means the instances "
        "are instantiated in the type, not that the result is independent of a probability model.", "",
        "| Endpoint | Backend operations in type | Backend laws in type | Logical dependencies |",
        "| --- | --- | --- | --- |"]
    for endpoint, typ, assumptions in answers:
        classes = sorted(set(re.findall(r"\b(?:Semantic\w+|MixedMeasure\w*)\b", typ)))
        ops = [c for c in classes if not c.endswith("Laws")]
        laws = [c for c in classes if c.endswith("Laws")]
        logical = re.findall(r"^([\w.]+)\s*:", assumptions, re.M)
        logical = [n for n in logical if n != "Axioms"]
        if "Axioms:" in assumptions and not logical:
            raise SystemExit("Cannot parse logical assumptions for " + endpoint)
        def listing(xs):
            return ", ".join("`" + x + "`" for x in xs) or "none"
        rows.append(f"| `{endpoint}` | {listing(ops)} | {listing(laws)} | {listing(logical)} |")
    for endpoint, typ, assumptions in answers:
        rows += ["", "## `" + endpoint + "`", "", "### Elaborated type", "", "```coq", typ, "```",
                 "", "### Logical assumptions (separate from capabilities)", "", "```text", assumptions, "```"]
    return "\n".join(rows) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = report(query())
    if args.check:
        if not REPORT.exists() or REPORT.read_text() != result:
            raise SystemExit("Capability baseline differs; review the elaborated types and assumptions before updating it.")
        print(f"Elaborated capability and logical-assumption baseline matches ({len(ENDPOINTS)} endpoints).")
    else:
        print(result, end="")
