#!/usr/bin/env python3
"""DS5a.2c: countable no-escape and nat dual-to-joint realization."""
import argparse
import re
from pathlib import Path

import audit_capabilities as compiled
from audit_domain_relational import check_answer
from audit_migration import frozen, without_comments

ROOT = Path(__file__).resolve().parents[1]
BASE = "f00478d"
REPORT = ROOT / "docs/DOMAIN_COUNTABLE_TRANSPORT_AUDIT.md"
SCALAR = "Prob/Backend/Common/CountableRealTransport"
MATRIX = "Prob/Domain/Matrix"
BRIDGE = "Prob/Backend/Common/DomainTransport"
TEST = "Regression/Probability/CountableTransportExistence"
NEW = {"theories/" + m + ".v" for m in (SCALAR, MATRIX, BRIDGE, TEST)}
GROUPS = {
    "PTree." + SCALAR.replace("/", "."): [
        "transport_cut_total", "transport_cut_prefix", "finite_transport_row_tail",
        "finite_cut_transport", "countable_cuts_closed", "countable_transport_no_escape",
        "transport_prefix_tight_exact", "countable_real_transport"],
    "PTree." + MATRIX.replace("/", "."): [
        "oval_sum_prefix_continuous", "oval_sum", "oval_series_atom", "oval_matrix_joint"],
    "PTree." + BRIDGE.replace("/", "."): [
        "oval_cut_eval", "oval_bidual_cut_hall", "oval_bidual_transport_matrix", "oval_bidual_coupled_nat"],
    "PTree." + TEST.replace("/", "."): [
        "successor_dual", "successor_joint_exists", "joint_keeps_actual_mass",
        "zero_mass_empty_relation", "unequal_mass_rejected", "escaping_pointwise_zero",
        "escaping_row_still_has_mass", "escaping_fails_no_escape_bound",
        "scalar_matrix_from_dual", "geometric_successor_joint_exists"],
}


def aggregate_after(text):
    for marker, additions in [
        ("Prob.Backend.Common.FinSupp", [SCALAR, BRIDGE]),
        ("Prob.Domain.MeasureModel", [MATRIX]),
        ("Regression.Probability.CountableTransport", [TEST]),
    ]:
        line = "Require PTree." + marker + ".\n"
        assert text.count(line) == 1, "Missing/duplicate aggregate marker"
        extra = "".join("Require PTree." + m.replace("/", ".") + ".\n" for m in additions)
        text = text.replace(line, line + extra if additions == [TEST] else extra + line)
    return text


def audit_sources(before, after):
    assert set(after) == set(before) | NEW, "Unexpected new/deleted theory module"
    for path, text in before.items():
        if path == "theories/Regression/Infrastructure/AllImports.v":
            text = aggregate_after(text)
        assert after[path] == text, "Frozen source changed: " + path
    for path in NEW:
        code = without_comments(after[path])
        assert not re.search(r"\b(?:Axiom|Axioms|Parameter|Parameters|Admitted|admit|Class)\b", code), path
        assert not re.search(r"\bfree_omega_qlift_sound\b", code), "FreeOmega realization is the next gate"
    for module in [SCALAR, MATRIX, BRIDGE]:
        code = without_comments(after["theories/" + module + ".v"])
        assert not re.search(r"\b(?:FreeOmega|free_omega_\w+|Semantic\w+|ptree|SubEnum|Inductive|CoInductive|Fixpoint)\b", code), "External mathematics only"
    scalar = without_comments(after["theories/" + SCALAR + ".v"])
    assert "OmegaVal" not in scalar and "tychonoff" in scalar and "finite_real_transport" in scalar
    bridge = without_comments(after["theories/" + BRIDGE + ".v"])
    assert "oval_atomic_tight" in bridge and "oval_matrix_joint" in bridge
    assert "Theorem oval_bidual_coupled_nat " in bridge
    return len(before), len(after)


def report():
    previous = compiled.GROUPS, compiled.ENDPOINTS
    try:
        compiled.GROUPS = GROUPS
        compiled.ENDPOINTS = [m + "." + n for m, ns in GROUPS.items() for n in ns]
        answers = compiled.query()
    finally:
        compiled.GROUPS, compiled.ENDPOINTS = previous
    lines = ["# Countable transport existence: compiled contracts", "",
             "Generated by `python3 tools/audit_countable_transport.py`; compare with `--check`.", "",
             f"Scope: {len(answers)} finite-cut, countable no-escape, matrix-joint and nat-existence endpoints.",
             "Established: bidual on arbitrary OmegaVal nat marginals implies an actual external joint.",
             "No finite-support, total-mass-one, supplied-plan or transport-existence capability premise.",
             "The endpoint does NOT yet assert general-carrier or FreeOmega qlift realization.",
             "The existing logical-axiom whitelist is unchanged.", ""]
    for name, typ, assumptions in answers:
        check_answer(name, typ, assumptions)
        if name.endswith("oval_bidual_coupled_nat"):
            assert "oval_bidual" in typ and "oval_coupled" in typ
            assert not re.search(r"\b(?:Semantic\w+|FreeOmega|free_omega_\w+)\b", typ)
        lines += ["## `" + name + "`", "", "```coq", typ, "```", "",
                  "```text", assumptions, "```", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source", action="store_true")
    args = parser.parse_args()
    if args.check or args.source:
        after = {p.relative_to(ROOT).as_posix(): p.read_text() for p in (ROOT / "theories").rglob("*.v")}
        counts = audit_sources(frozen(BASE), after)
        print(f"Countable transport isolation: {counts[0]} frozen modules; {counts[1]} now; aggregate insertions only.")
    if not args.source:
        result = report()
        if args.check:
            assert REPORT.read_text() == result, "Countable transport contracts changed"
            print("Countable nat dual-to-joint contracts and assumptions match.")
        else:
            print(result, end="")
