#!/usr/bin/env python3
"""DS5a.3: countable-carrier decoding and final SubEnum qlift realization."""
import argparse
import re
from pathlib import Path

import audit_capabilities as compiled
from audit_domain_relational import check_answer
from audit_migration import frozen, without_comments

ROOT = Path(__file__).resolve().parents[1]
BASE = "b91df98"
REPORT = ROOT / "docs/DOMAIN_JOINT_SOUNDNESS_AUDIT.md"
EXTERNAL = "Prob/Backend/Common/CountableCoupling"
BRIDGE = "Prob/Backend/SubEnum/FreeOmega/JointSoundness"
TEST = "Regression/Probability/FreeOmegaJointDomain"
NEW = {"theories/" + m + ".v" for m in (EXTERNAL, BRIDGE, TEST)}
GROUPS = {
    "PTree." + EXTERNAL.replace("/", "."): [
        "oval_bidual_coupled_on_enumerations", "oval_bidual_coupled", "oval_countable_coupling_iff"],
    "PTree." + BRIDGE.replace("/", "."): [
        "free_omega_qlift_sound", "free_omega_qlift_eq_sound_via_joint",
        "free_omega_qlift_joint_mass_support"],
    "PTree." + TEST.replace("/", "."): [
        "empty_carrier_joint", "type_carrier_joint", "duplicate_invalid_codes_joint",
        "heterogeneous_joint_through_invalid", "invalid_middle_stays_invalid",
        "equality_joint_recovers_ds3", "empty_endpoint_qlift_joint",
        "partial_heterogeneous_qlift", "partial_joint_keeps_mass_and_support",
        "geometric_quotient_joint", "qlift_alone_still_not_admissible",
        "type_valued_qlift_joint"],
}


def aggregate_after(text):
    for marker, addition in [
        ("Prob.Backend.Common.CountableRealTransport", EXTERNAL),
        ("Prob.Backend.SubEnum.FreeOmega.NativeCoupling", BRIDGE),
        ("Regression.Probability.FreeOmegaQuotientDomain", TEST),
    ]:
        line = "Require PTree." + marker + ".\n"
        assert text.count(line) == 1, "Missing/duplicate aggregate marker"
        text = text.replace(line, "Require PTree." + addition.replace("/", ".") + ".\n" + line)
    return text


def audit_sources(before, after):
    assert set(after) == set(before) | NEW, "Unexpected new/deleted theory module"
    for path, text in before.items():
        if path == "theories/Regression/Infrastructure/AllImports.v":
            text = aggregate_after(text)
        assert after[path] == text, "Frozen source changed: " + path
    for path in NEW:
        code = without_comments(after[path])
        assert not re.search(r"\b(?:Axiom|Axioms|Parameter|Parameters|Admitted|admit|Class)\b", code), path
    for module in [EXTERNAL, BRIDGE]:
        code = without_comments(after["theories/" + module + ".v"])
        assert not re.search(r"\b(?:Inductive|CoInductive|Fixpoint|CoFixpoint|induction|elim)\b", code), "Composition only"
        assert len(re.findall(r"\bTheorem\b", code)) == 3
    external = without_comments(after["theories/" + EXTERNAL + ".v"])
    assert not re.search(r"\b(?:FreeOmega|free_omega_\w+|Semantic\w+|ptree|SubEnum)\b", external)
    for name in ["oval_bidual_coupled_nat", "oval_joint_decode", "oval_countable_transport_reduction"]:
        assert name in external, "Missing existing coding/transport/decode bridge"
    bridge = without_comments(after["theories/" + BRIDGE + ".v"])
    assert "Theorem free_omega_qlift_sound " in bridge
    assert "free_omega_qlift_countable_constraints" in bridge and "oval_bidual_coupled" in bridge
    assert "FOQL" not in bridge, "Do not analyze qlift constructors or intermediate validity"
    return len(before), len(after)


def report():
    previous = compiled.GROUPS, compiled.ENDPOINTS
    try:
        compiled.GROUPS = GROUPS
        compiled.ENDPOINTS = [m + "." + n for m, ns in GROUPS.items() for n in ns]
        answers = compiled.query()
    finally:
        compiled.GROUPS, compiled.ENDPOINTS = previous
    lines = ["# General qlift joint soundness: compiled contracts", "",
             "Generated by `python3 tools/audit_domain_joint.py`; compare with `--check`.", "",
             f"Scope: {len(answers)} arbitrary-carrier, SubEnum soundness and regression endpoints.",
             "Established: qlift R with admissible FreeOmega SubEnum endpoints has an external joint.",
             "No admissibility of raw intermediate terms, supplied plan, or transport capability is required.",
             "Countability is a property of endpoint support, not a typeclass on the result carriers.",
             "This is soundness, NOT completeness of syntactic qlift; no MathComp-native endpoint is claimed.",
             "The existing logical-axiom whitelist is unchanged.", ""]
    for name, typ, assumptions in answers:
        check_answer(name, typ, assumptions)
        if name.endswith(".free_omega_qlift_sound"):
            assert "free_omega_admissible" in typ and "SubEnum" in typ and "oval_coupled" in typ
            assert not re.search(r"\b(?:Semantic\w+Laws|MathCompCouplingGluing)\b", typ)
        if name.startswith("PTree." + EXTERNAL.replace("/", ".") + "."):
            assert not re.search(r"\b(?:Semantic\w+|FreeOmega|free_omega_\w+)\b", typ)
        lines += ["## `" + name + "`", "", "```coq", typ, "```", "",
                  "```text", assumptions, "```", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source", action="store_true")
    args = parser.parse_args()
    if args.check or args.source:
        after = {p.relative_to(ROOT).as_posix(): p.read_text() for p in (ROOT / "theories").rglob("*.v")}
        counts = audit_sources(frozen(BASE), after)
        print(f"Joint soundness isolation: {counts[0]} frozen modules; {counts[1]} now; aggregate insertions only.")
    if not args.source:
        result = report()
        if args.check:
            assert REPORT.read_text() == result, "Joint soundness contracts changed"
            print("General joint soundness contracts and assumptions match.")
        else:
            print(result, end="")
