#!/usr/bin/env python3
"""DS3 compiled equality soundness and exact frozen-source audit (read-only)."""
import argparse
import re
from pathlib import Path

import audit_capabilities as compiled
from audit_domain_soundness import ALLOWED_AXIOMS
from audit_migration import frozen, without_comments

ROOT = Path(__file__).resolve().parents[1]
BASE = "7a3bf82"
REPORT = ROOT / "docs/DOMAIN_DS3_AUDIT.md"
CORE = "Prob/Backend/SubEnum/FreeOmega/QuotientSoundness"
REGRESSION = "Regression/Probability/FreeOmegaQuotientDomain"
NEW = {"theories/" + p + ".v" for p in (CORE, REGRESSION)}
ENDPOINTS = ["free_omega_qlift_eq_admissible", "free_omega_qlift_eq_sound",
             "free_omega_sem_eq_admissible", "free_omega_sem_eq_sound"]
GROUPS = {
    "PTree.Prob.Backend.SubEnum.FreeOmega.UpperQuotient": ["free_omega_qlift_eq_upper"],
    "PTree.Prob.Backend.SubEnum.FreeOmega.Admissibility": ["free_omega_admissible_ext"],
    "PTree." + CORE.replace("/", "."): ENDPOINTS,
    "PTree." + REGRESSION.replace("/", "."): [
        "constant_to_invalid", "invalid_to_ret", "equality_through_invalid_middle",
        "retry_quotient", "invalid_middle_really_invalid", "constant_valid_by_quotient",
        "invalid_middle_does_not_block_soundness", "equality_alone_is_not_validity",
        "invalid_not_equal_to_valid", "retry_valid_by_quotient",
        "unbounded_retry_quotient_sound", "soundness_ignores_validity_proofs",
        "quotient_cannot_erase_missing_mass",
    ],
}


def aggregate_after(text):
    for marker, module in [
        ("Require PTree.Prob.Backend.SubEnum.FreeOmega.NativeTransport.\n", CORE),
        ("Require PTree.Regression.Probability.FreeOmegaDomain.\n", REGRESSION),
    ]:
        assert text.count(marker) == 1, "Missing/duplicate frozen aggregate marker"
        text = text.replace(marker, marker + "Require PTree." + module.replace("/", ".") + ".\n")
    return text


def audit_sources(before, after):
    assert set(after) == set(before) | NEW, "Unexpected new/deleted theory module"
    aggregate = "theories/Regression/Infrastructure/AllImports.v"
    for path, text in before.items():
        if path == aggregate:
            text = aggregate_after(text)
        assert after[path] == text, "Frozen source changed: " + path
    for path in NEW:
        code = without_comments(after[path])
        assert not re.search(r"\b(?:Axiom|Axioms|Parameter|Parameters|Admitted|admit)\b", code), path
    core = without_comments(after["theories/" + CORE + ".v"])
    assert re.findall(r"^Theorem (\w+)", core, re.M) == ENDPOINTS, "Unexpected DS3 theorem scope"
    assert not re.search(r"\b(?:Inductive|CoInductive|Fixpoint|induction|elim)\b", core), "DS3 must use the raw evaluator bridge"
    return len(before), len(after)


def report():
    previous = compiled.GROUPS, compiled.ENDPOINTS
    try:
        compiled.GROUPS = GROUPS
        compiled.ENDPOINTS = [m + "." + n for m, ns in GROUPS.items() for n in ns]
        answers = compiled.query()
    finally:
        compiled.GROUPS, compiled.ENDPOINTS = previous
    lines = ["# DS3 compiled quotient-equality soundness audit", "",
             "Generated by `python3 tools/audit_domain_quotient.py`; compare with `--check`.", "",
             f"Scope: {len(answers)} bridge, theorem and regression endpoints; not a whole-library kernel audit.",
             "SubEnum-qualified equality only, on admissible endpoints; no general joint-coupling realization.",
             "The four core endpoints introduce no generic Semantic capability premise.",
             "The logical-axiom whitelist is unchanged from DS2. The existing raw evaluator bridge and validity-extensionality helper are audited alongside their clients.",
             "Prior DS1/DS2/mainline snapshots remain separate and are not regenerated.", ""]
    for name, typ, assumptions in answers:
        assert not re.search(r"\b(?:ptree|peutt)\b", typ), name
        assert not re.search(r":\s*@?(?:\w+\.)*Semantic\w+\b", typ), name
        axioms = {n for n in re.findall(r"^([\w.]+)\s*:", assumptions, re.M) if n != "Axioms"}
        if "Axioms:" in assumptions:
            assert axioms, "Unparsed assumptions: " + name
        assert axioms <= ALLOWED_AXIOMS, (name, axioms - ALLOWED_AXIOMS)
        if name.startswith("PTree." + CORE.replace("/", ".") + "."):
            assert "free_omega_admissible" in typ, "Missing validity boundary: " + name
            if name.endswith("_sound"):
                assert "oval_eq" in typ, "Wrong semantic equality: " + name
            if ".free_omega_sem_eq_" in name:
                assert "FreeOmegaObservableSemanticMeasure" in typ, "Wrong sem_eq instance: " + name
        lines += ["## `" + name + "`", "", "```coq", typ, "```", "",
                  "```text", assumptions, "```", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source", action="store_true")
    args = parser.parse_args()
    if args.check or args.source:
        after = {p.relative_to(ROOT).as_posix(): p.read_text() for p in (ROOT / "theories").rglob("*.v")}
        counts = audit_sources(frozen(BASE), after)
        print(f"DS3 source isolation: {counts[0]} frozen modules unchanged except exact AllImports additions; {counts[1]} modules now.")
    if not args.source:
        text = report()
        if args.check:
            assert REPORT.read_text() == text, "DS3 compiled report changed"
            print("DS3 compiled signatures and logical assumptions agree with the checked report.")
        else:
            print(text, end="")
