#!/usr/bin/env python3
"""Finite real Hall existence; countable transport still remains open."""
import argparse
import re
from pathlib import Path

import audit_capabilities as compiled
from audit_domain_relational import check_answer
from audit_migration import frozen, without_comments

ROOT = Path(__file__).resolve().parents[1]
BASE = "c189a2e"
REPORT = ROOT / "docs/DOMAIN_REAL_TRANSPORT_AUDIT.md"
MATH = "Prob/Backend/Common/RealTransport"
TEST = "Regression/Probability/RealTransport"
NEW = {"theories/" + m + ".v" for m in (MATH, TEST)}
GROUPS = {
    "PTree." + MATH.replace("/", "."): [
        "finite_capacity_subtransport", "transport_floor_bounds",
        "real_transport_hall", "finite_real_transport_approx",
        "transport_compact_nested", "transport_eps_small", "transport_eps_limit",
        "finite_real_subtransport", "finite_real_transport",
        "finite_real_transport_of_tests", "finite_real_transport_relation"],
    "PTree." + TEST.replace("/", "."): [
        "diagonal_real_mass", "sqrt_weight_transport", "unused_target_capacity",
        "split_real_mass", "empty_source", "zero_demand_empty_target",
        "positive_demand_empty_target_impossible"],
}


def aggregate_after(text):
    for previous, new in [
        ("Prob.Backend.Common.RealSubTypes", MATH.replace("/", ".")),
        ("Regression.Probability.OmegaValMeasure", TEST.replace("/", ".")),
    ]:
        marker = "Require PTree." + previous + ".\n"
        assert text.count(marker) == 1, "Missing/duplicate aggregate marker"
        text = text.replace(marker, marker + "Require PTree." + new + ".\n")
    return text


def audit_sources(before, after):
    assert set(after) == set(before) | NEW, "Unexpected new/deleted theory module"
    for path, text in before.items():
        if path == "theories/Regression/Infrastructure/AllImports.v":
            text = aggregate_after(text)
        assert after[path] == text, "Frozen source changed: " + path
    for path in NEW:
        code = without_comments(after[path])
        assert not re.search(r"\b(?:Axiom|Axioms|Parameter|Parameters|Admitted|admit|Class)\b", code), path
        assert not re.search(r"\b(?:countable_transport_exists|free_omega_qlift_sound)\b", code), "Countable realization remains open"
    code = without_comments(after["theories/" + MATH + ".v"])
    assert not re.search(r"\b(?:FreeOmega|free_omega_\w+|OmegaVal|Semantic\w+|ptree|SubEnum|Inductive|CoInductive|Fixpoint)\b", code), "Independent finite mathematics only"
    assert "capacity_hall_matching" in code and "tychonoff" in code
    for endpoint in ["finite_real_subtransport", "finite_real_transport"]:
        assert re.search(r"Theorem " + endpoint + r"\b", code), "Missing existence theorem"
    return len(before), len(after)


def report():
    previous = compiled.GROUPS, compiled.ENDPOINTS
    try:
        compiled.GROUPS = GROUPS
        compiled.ENDPOINTS = [m + "." + n for m, ns in GROUPS.items() for n in ns]
        answers = compiled.query()
    finally:
        compiled.GROUPS, compiled.ENDPOINTS = previous
    lines = ["# Finite real Hall transport: compiled contracts", "",
             "Generated by `python3 tools/audit_real_transport.py`; compare with `--check`.", "",
             f"Scope: {len(answers)} finite-real existence, approximation, compactness and regression endpoints.",
             "Real finite matrices are constructed from Hall/test inequalities. No transport-existence axiom or capability is assumed.",
             "This is NOT countable transport existence or general qlift joint realization. DS5a.2 remains OPEN.",
             "The existing logical-axiom whitelist is unchanged.", ""]
    for name, typ, assumptions in answers:
        check_answer(name, typ, assumptions)
        assert not re.search(r"\b(?:FreeOmega|OmegaVal|Semantic\w+|ptree)\b", typ), name
        lines += ["## `" + name + "`", "", "```coq", typ, "```", "",
                  "```text", assumptions, "```", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source", action="store_true")
    args = parser.parse_args()
    if args.check or args.source:
        after = {p.relative_to(ROOT).as_posix(): p.read_text() for p in (ROOT / "theories").rglob("*.v")}
        counts = audit_sources(frozen(BASE), after)
        print(f"Finite transport isolation: {counts[0]} frozen modules; {counts[1]} now; exact aggregate insertions only.")
    if not args.source:
        result = report()
        if args.check:
            assert REPORT.read_text() == result, "Finite transport contracts changed"
            print("Finite real existence contracts match. Countable transport remains OPEN.")
        else:
            print(result, end="")
