#!/usr/bin/env python3
"""DS1b compiled standard-measure correspondence audit (read-only)."""
import argparse
import re
from pathlib import Path

import audit_capabilities as compiled
from audit_domain import ALLOWED_AXIOMS

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/DOMAIN_DS1B_AUDIT.md"
GROUPS = {
    "PTree.Prob.Domain.MeasureModel": [
        "oval_carrier", "oval_set_measure", "oval_set_measure_sigma_additive",
        "oval_subprobability", "oval_simple_integral", "oval_integral_recovery",
        "measure_oval_integral_bounds", "measure_oval_integral_finite",
        "measure_oval_eval", "measure_oval_evalE", "measure_oval_eval_continuous",
        "measure_oval_laws", "measure_oval", "oval_measure_roundtrip",
        "measure_oval_roundtrip", "oval_measure_extensional",
        "oval_missing_mass", "oval_complete", "oval_complete_mass",
        "oval_probability", "oval_probability_setT", "probability_oval",
        "probability_oval_eval", "oval_probability_integral",
        "oval_probability_bottom", "oval_probability_values",
        "oval_probability_roundtrip", "probability_oval_roundtrip",
    ],
    "PTree.Regression.Probability.OmegaValMeasure": [
        "bottom_is_standard_probability", "bottom_mass_one",
        "dirac_missing_mass_zero", "distinct_returned_diracs",
        "half_mass_at_bottom", "half_mass_at_true",
        "bounded_expectation_recovered", "arbitrary_standard_probability_recovered",
        "empty_carrier_probability_is_bottom",
    ],
}


def report():
    previous = compiled.GROUPS, compiled.ENDPOINTS
    try:
        compiled.GROUPS = GROUPS
        compiled.ENDPOINTS = [m + "." + n for m, ns in GROUPS.items() for n in ns]
        answers = compiled.query()
    finally:
        compiled.GROUPS, compiled.ENDPOINTS = previous
    lines = ["# DS1b compiled standard-measure audit", "",
             "Generated by `python3 tools/audit_domain_measure.py`; compare with `--check`.", "",
             f"Scope: {len(answers)} selected model and regression endpoints; not a whole-library kernel audit.",
             "The DS1a snapshot is separate and unchanged. The allowed logical-axiom list is exactly DS1a's list.",
             "No PTree Semantic capability, FreeOmega, or ptree premise is permitted.",
             "Generic recovery uses measurability; the full correspondence uses the discrete lifted carrier.", ""]
    for name, typ, assumptions in answers:
        assert not re.search(r"\b(?:Semantic\w+|FreeOmega|ptree)\b", typ), name
        axioms = {n for n in re.findall(r"^([\w.]+)\s*:", assumptions, re.M) if n != "Axioms"}
        if "Axioms:" in assumptions:
            assert axioms, "Unparsed assumptions: " + name
        assert axioms <= ALLOWED_AXIOMS, (name, axioms - ALLOWED_AXIOMS)
        lines += ["## `" + name + "`", "", "```coq", typ, "```", "",
                  "```text", assumptions, "```", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = report()
    if args.check:
        assert REPORT.read_text() == text, "DS1b report differs; review the compiled change."
        print("DS1b compiled signatures and logical assumptions agree with the checked report.")
    else:
        print(text, end="")
