#!/usr/bin/env python3
"""DS1a compiled signatures/logical assumptions, independent of old snapshots."""
import argparse
import re
from pathlib import Path

import audit_capabilities as compiled

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/DOMAIN_DS1A_AUDIT.md"
GROUPS = {
    "PTree.Prob.Domain.Expectation": [
        "oval_test", "OmegaValLaws", "OmegaVal", "oval_eq", "oval_le",
        "oval_laws_ext", "oval_eq_equivalence", "oval_le_refl", "oval_le_trans",
        "oval_le_antisym", "oval_eval_bounds", "oval_mass", "oval_bottom",
        "oval_ret", "oval_bind", "oval_lub", "oval_bottom_le",
        "oval_lub_upper", "oval_lub_least", "oval_lub_proper",
        "oval_bind_ret_l", "oval_bind_ret_r", "oval_bind_assoc",
        "oval_bind_mono", "oval_bind_proper", "oval_bind_lub_l",
        "oval_bind_lub_r", "oval_bind_double_diagonal",
    ],
    "PTree.Regression.Probability.OmegaVal": [
        "distinct_diracs", "bottom_is_not_dirac", "delayed_lub",
        "alternating_not_increasing", "both_arguments_grow",
        "empty_carrier_has_zero_mass", "high_right_unit",
        "equality_ignores_unbounded_tests", "evaluators_still_differ",
    ],
}
ALLOWED_AXIOMS = {
    "boolp.propositional_extensionality",
    "boolp.functional_extensionality_dep",
    "FunctionalExtensionality.functional_extensionality_dep",
    "boolp.constructive_indefinite_description",
}


def report():
    # Reuse the marker/error-checked compiled query protocol, not its frozen
    # Gate A endpoint list or baseline. No baseline is overwritten here.
    old_groups, old_endpoints = compiled.GROUPS, compiled.ENDPOINTS
    try:
        compiled.GROUPS = GROUPS
        compiled.ENDPOINTS = [m + "." + n for m, ns in GROUPS.items() for n in ns]
        answers = compiled.query()
    finally:
        compiled.GROUPS, compiled.ENDPOINTS = old_groups, old_endpoints
    lines = ["# DS1a compiled domain audit", "",
             "Generated by `python3 tools/audit_domain.py`; compare with `--check`.", "",
             f"Scope: {len(answers)} selected domain and regression endpoints. This is not a whole-library kernel audit.",
             "No SemanticMeasure/SemanticOmega, FreeOmega or PTree premise is permitted in these types.",
             "MathComp realType supplies the scalar structure. Logical dependencies below include classical choice/extensionality; this is not a constructivity claim.", ""]
    for name, typ, assumptions in answers:
        assert not re.search(r"\b(?:Semantic\w+|FreeOmega|ptree)\b", typ), name
        axioms = {n for n in re.findall(r"^([\w.]+)\s*:", assumptions, re.M) if n != "Axioms"}
        if "Axioms:" in assumptions:
            assert axioms, "Unparsed assumptions: " + name
        assert axioms <= ALLOWED_AXIOMS, (name, axioms - ALLOWED_AXIOMS)
        lines += ["## `" + name + "`", "", "```coq", typ, "```", "",
                  "```text", assumptions, "```", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = report()
    if args.check:
        assert REPORT.read_text() == text, "DS1a report differs; review the compiled change."
        print("DS1a compiled signatures and logical assumptions agree with the checked report.")
    else:
        print(text, end="")
