#!/usr/bin/env python3
"""DS5a.2 preparation: atomic series/transport reduction, NOT existence."""
import argparse
import re
from pathlib import Path

import audit_capabilities as compiled
from audit_domain_relational import check_answer
from audit_migration import frozen, without_comments

ROOT = Path(__file__).resolve().parents[1]
BASE = "086f2c1"
REPORT = ROOT / "docs/DOMAIN_TRANSPORT_PREPARATION_AUDIT.md"
ATOMIC = "Prob/Domain/Atomic"
SERIES = "Prob/Domain/Series"
TRANSPORT = "Prob/Domain/CountableTransport"
REGRESSION = "Regression/Probability/CountableTransport"
NEW = {"theories/" + p + ".v" for p in (ATOMIC, SERIES, TRANSPORT, REGRESSION)}
GROUPS = {
    "PTree.Prob.Domain.Atomic": [
        "oval_atom", "oval_atom_bounds", "oval_prefix_eval",
        "oval_atomic_representation", "oval_atomic_mass", "oval_atomic_ext",
        "oval_prefix_mass_le", "oval_atomic_tight", "oval_atomic_tail"],
    "PTree.Prob.Domain.Series": [
        "oval_weighted_prefix_continuous", "oval_series", "oval_series_roundtrip",
        "oval_series_concentrated", "oval_transport_plan_joint"],
    "PTree.Prob.Domain.CountableTransport": [
        "oval_dual_ae_restrict", "oval_coded_mass", "oval_coded_representation",
        "oval_coded_bidual", "oval_joint_decode", "oval_countable_transport_reduction"],
    "PTree.Regression.Probability.CountableTransport": [
        "successor_plan", "subprobability_tail_is_actual_mass", "duplicate_decode_joint",
        "invalid_code_not_supported", "duplicate_codes_not_injective",
        "decode_preserves_missing_mass", "duplicated_cover_dual",
        "zero_decoded_joint", "atoms_determine_measure", "geometric_successor_plan"],
}


def aggregate_after(text):
    for marker, addition in [
        ("Require PTree.Prob.Domain.Countable.\n",
         "Require PTree.Prob.Domain.Atomic.\nRequire PTree.Prob.Domain.Countable.\n"
         "Require PTree.Prob.Domain.CountableTransport.\n"),
        ("Require PTree.Prob.Domain.MeasureModel.\n",
         "Require PTree.Prob.Domain.MeasureModel.\nRequire PTree.Prob.Domain.Series.\n"),
        ("Require PTree.Regression.Probability.CorrelatedSampleAlgebra.\n",
         "Require PTree.Regression.Probability.CorrelatedSampleAlgebra.\n"
         "Require PTree.Regression.Probability.CountableTransport.\n"),
    ]:
        assert text.count(marker) == 1, "Missing/duplicate frozen aggregate marker"
        text = text.replace(marker, addition)
    return text


def audit_sources(before, after):
    assert set(after) == set(before) | NEW, "Unexpected new/deleted theory module"
    for path, text in before.items():
        if path == "theories/Regression/Infrastructure/AllImports.v":
            text = aggregate_after(text)
        assert after[path] == text, "Frozen source changed: " + path
    for path in NEW:
        code = without_comments(after[path])
        assert not re.search(r"\b(?:Axiom|Axioms|Parameter|Parameters|Admitted|admit|Class)\b", code), path
        assert not re.search(r"\b(?:countable_transport_exists|free_omega_qlift_sound)\b", code), "Existence not established by this increment"
        if path.startswith("theories/Prob/Domain/"):
            assert not re.search(r"\b(?:FreeOmega|free_omega_\w+|Semantic\w+|ptree|Inductive|CoInductive|Fixpoint)\b", code), "Domain is independent, not new syntax"
    return len(before), len(after)


def report():
    previous = compiled.GROUPS, compiled.ENDPOINTS
    try:
        compiled.GROUPS = GROUPS
        compiled.ENDPOINTS = [m + "." + n for m, ns in GROUPS.items() for n in ns]
        answers = compiled.query()
    finally:
        compiled.GROUPS, compiled.ENDPOINTS = previous
    lines = ["# Countable transport preparation: compiled contracts", "",
             "Generated by `python3 tools/audit_domain_transport.py`; compare with `--check`.", "",
             f"Scope: {len(answers)} atomic-series, tightness, transport-plan and coding endpoints.",
             "This increment does NOT establish Hall/bidual-to-joint existence. DS5a.2 remains OPEN.",
             "The joint constructor takes actual nonnegative scalar weights with exact marginal sums; no transport-existence capability is assumed.",
             "The domain remains independent. Earlier signatures and logical whitelists are unchanged.", ""]
    for name, typ, assumptions in answers:
        check_answer(name, typ, assumptions)
        lines += ["## `" + name + "`", "", "```coq", typ, "```", "",
                  "```text", assumptions, "```", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source", action="store_true")
    args = parser.parse_args()
    if args.check or args.source:
        after = {p.relative_to(ROOT).as_posix(): p.read_text() for p in (ROOT / "theories").rglob("*.v")}
        counts = audit_sources(frozen(BASE), after)
        print(f"Transport preparation isolation: {counts[0]} frozen modules; {counts[1]} modules now; exact aggregate insertions only.")
    if not args.source:
        result = report()
        if args.check:
            assert REPORT.read_text() == result, "Transport preparation compiled report changed"
            print("Atomic/reduction/plan contracts match. General transport existence remains OPEN.")
        else:
            print(result, end="")
