#!/usr/bin/env python3
"""DS2 SubEnum/FreeOmega external-model compiled audit (read-only)."""
import argparse
import re
from pathlib import Path

import audit_capabilities as compiled
from audit_domain import ALLOWED_AXIOMS as DOMAIN_AXIOMS

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/DOMAIN_DS2_AUDIT.md"
GROUPS = {
    # Existing bridges make the origin of inherited classical/UIP dependencies
    # inspectable in the same compiled session as their new clients.
    "PTree.Prob.Backend.SubEnum.FreeOmega.UpperCoupling": [
        "subenum_lift_real_expect", "free_omega_upper_ae_ext",
        "free_omega_upper_approx_mono",
    ],
    "PTree.Prob.Backend.SubEnum.Domain": [
        "subenum_domain_laws", "subenum_domain", "subenum_domain_ret",
        "subenum_domain_zero", "subenum_domain_bind", "subenum_sem_eq_sound",
        "subenum_sem_lift_test_sound",
    ],
    "PTree.Prob.Backend.SubEnum.FreeOmega.Admissibility": [
        "free_omega_admissible", "free_omega_domain", "free_omega_domain_denotes",
        "free_omega_admissible_iff_denotes", "free_omega_admissible_ext",
        "admissible_ret", "admissible_zero", "admissible_sample",
        "free_omega_domain_increasing", "admissible_lub", "admissible_lub_approx",
        "admissible_bind", "admissible_support_kernel_valid",
        "admissible_bind_ae", "admissible_sample_ae",
    ],
    "PTree.Prob.Backend.SubEnum.FreeOmega.DomainSoundness": [
        "free_omega_domain_spec", "free_omega_domain_proof_independent",
        "free_omega_denote_ret", "free_omega_denote_zero",
        "free_omega_denote_sample", "free_omega_denote_native",
        "free_omega_denote_bind", "free_omega_denote_bind_ae",
        "free_omega_denote_sample_ae", "free_omega_denote_lub",
        "free_omega_denote_approx", "free_omega_denote_approx_test",
        "free_omega_domain_increasing_of_approx",
    ],
    "PTree.Regression.Probability.FreeOmegaDomain": [
        "alternating_bool_not_admissible", "alternating_has_no_domain_model",
        "null_weight_bad_branch_admissible", "null_weight_bad_branch_bind_admissible",
        "null_weight_branch_really_invalid", "null_weight_sample_denotes",
        "positive_bad_branch_not_admissible", "increasing_lub_admissible",
        "increasing_lub_denotes", "approximation_denotes_order", "native_bind_denotes",
        "unbounded_retry_admissible", "unbounded_retry_denotes_lub",
    ],
}
# These are dependencies of the EXISTING finite coupling / structural AE
# bridges audited above, not additional semantic/model capabilities.
ALLOWED_AXIOMS = DOMAIN_AXIOMS | {
    "Eqdep.Eq_rect_eq.eq_rect_eq", "Description.constructive_definite_description",
    "Classical_Prop.classic",
}


def report():
    previous = compiled.GROUPS, compiled.ENDPOINTS
    try:
        compiled.GROUPS = GROUPS
        compiled.ENDPOINTS = [m + "." + n for m, ns in GROUPS.items() for n in ns]
        answers = compiled.query()
    finally:
        compiled.GROUPS, compiled.ENDPOINTS = previous
    lines = ["# DS2 compiled admissibility/domain-soundness audit", "",
             "Generated by `python3 tools/audit_domain_soundness.py`; compare with `--check`.", "",
             f"Scope: {len(answers)} selected SubEnum, FreeOmega and regression endpoints; not a whole-library kernel audit.",
             "DS1a/DS1b and the mainline snapshots are separate and unchanged.",
             "All native carriers are concrete SubEnum; no arbitrary backend-capability premise is introduced.",
             "Existing bridge probes record inherited eq_rect_eq, Coq classic/definite description, and the DS1 logical axioms; exact per-endpoint assumptions follow.",
             "No quotient-equality, general joint-coupling, or stable-hitting soundness claim is made here.", ""]
    for name, typ, assumptions in answers:
        assert not re.search(r"\b(?:ptree|peutt)\b", typ), name
        assert not re.search(r":\s*@?(?:\w+\.)*Semantic\w+\b", typ), name
        axioms = {n for n in re.findall(r"^([\w.]+)\s*:", assumptions, re.M) if n != "Axioms"}
        if "Axioms:" in assumptions:
            assert axioms, "Unparsed assumptions: " + name
        assert axioms <= ALLOWED_AXIOMS, (name, axioms - ALLOWED_AXIOMS)
        lines += ["## `" + name + "`", "", "```coq", typ, "```", "",
                  "```text", assumptions, "```", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = report()
    if args.check:
        assert REPORT.read_text() == text, "DS2 report differs; review the compiled change."
        print("DS2 compiled signatures and logical assumptions agree with the checked report.")
    else:
        print(text, end="")
